import{useState,useEffect,useCallback,useRef,useMemo,type ReactNode}from'react';
import{ld,sv,uid,td,getRank,getTitle,RC,defProf,defStats,defDL,defEdu,calcGPA,
type Prof,type Stats,type Quest,type Ach,type Workout,type StudySes,type CodingSes,
type Tx,type Goal,type Habit,type Task,type Note,type FC,type QR,type DL,type WtEntry,type WaterEntry,
type EduProfile,type Semester,type SemSubject,type MediaItem}from'./store';
import{getB12Questions,getSubjectsForStream,type B12Question}from'./data/board12';
import{getQuestions}from'./data/questions';
import{articles,categories as KC}from'./data/knowledge';
import{collegePrograms,countries,boards as eduBoards}from'./data/education';

const C={c:'#00E5FF',p:'#7B2FFF',bg:'#050816'};
const F={o:"'Orbitron',sans-serif",r:"'Rajdhani',sans-serif",m:"'JetBrains Mono',monospace"};
type Tab='home'|'fit'|'study'|'board'|'exam'|'cards'|'code'|'math'|'finance'|'prod'|'know'|'stats'|'cfg'|'college'|'media';

const TABS:{id:Tab;icon:string;l:string}[]=[
{id:'home',icon:'⬡',l:'Home'},{id:'fit',icon:'💪',l:'Fit'},{id:'study',icon:'📚',l:'Study'},
{id:'board',icon:'🎓',l:'Board'},{id:'college',icon:'🏛️',l:'Uni'},{id:'exam',icon:'📝',l:'Exam'},
{id:'cards',icon:'🃏',l:'Cards'},{id:'code',icon:'💻',l:'Code'},{id:'math',icon:'🔢',l:'Math'},
{id:'finance',icon:'💰',l:'$'},{id:'prod',icon:'🎯',l:'Tasks'},{id:'media',icon:'🖼️',l:'Media'},
{id:'know',icon:'📖',l:'Learn'},{id:'stats',icon:'📊',l:'Stats'},{id:'cfg',icon:'⚙️',l:'Cfg'}];

/* ═══ UI ═══ */
const GL=({color=C.c,cl=''}:{color?:string;cl?:string})=><div className={`h-[1px] ${cl}`} style={{background:`linear-gradient(90deg,transparent,${color},transparent)`}}/>;
const ST=({children,color=C.c}:{children:ReactNode;color?:string})=><div className="flex items-center gap-3 mb-4"><span className="text-[11px] font-bold tracking-[3px] whitespace-nowrap" style={{fontFamily:F.o,color}}>{children}</span><div className="flex-1 h-[1px]" style={{background:`linear-gradient(90deg,${color}40,transparent)`}}/></div>;
const Cd=({children,cl='',glow='',onClick}:{children:ReactNode;cl?:string;glow?:string;onClick?:()=>void})=><div onClick={onClick} className={`rounded-xl border p-3.5 ${onClick?'cursor-pointer active:scale-[.98] transition-transform':''} ${cl}`} style={{background:'rgba(255,255,255,.02)',borderColor:glow?`${glow}25`:'rgba(255,255,255,.04)',boxShadow:glow?`0 0 15px ${glow}06`:'none'}}>{children}</div>;
const Bt=({children,color=C.c,v='solid',cl='',onClick,disabled,sm}:{children:ReactNode;color?:string;v?:'solid'|'outline'|'ghost';cl?:string;onClick?:()=>void;disabled?:boolean;sm?:boolean})=>{
const b=sm?'px-3 py-1.5 text-[10px]':'px-4 py-2.5 text-xs';
const s={solid:{background:`linear-gradient(135deg,${color},${color}CC)`,color:'#fff',border:'none',boxShadow:`0 0 12px ${color}25`},outline:{background:'transparent',color,border:`1px solid ${color}40`},ghost:{background:`${color}08`,color,border:'none'}}[v];
return<button onClick={onClick} disabled={disabled} className={`${b} rounded-lg font-bold tracking-wider transition-all active:scale-95 disabled:opacity-30 ${cl}`} style={{fontFamily:F.r,...s}}>{children}</button>;};
const In=({value,onChange,placeholder='',type='text',cl=''}:{value:string;onChange:(v:string)=>void;placeholder?:string;type?:string;cl?:string})=>
<input type={type} value={value} onChange={e=>onChange(e.target.value)} placeholder={placeholder} className={`w-full px-3 py-2.5 rounded-lg text-sm text-white placeholder:text-gray-600 outline-none border focus:border-[#00E5FF30] ${cl}`} style={{background:'rgba(255,255,255,.03)',borderColor:'rgba(255,255,255,.06)',fontFamily:F.r}}/>;
const Sl=({value,onChange,options}:{value:string;onChange:(v:string)=>void;options:{v:string;l:string}[]})=>
<select value={value} onChange={e=>onChange(e.target.value)} className="w-full px-3 py-2.5 rounded-lg text-sm text-white outline-none border" style={{background:'rgba(10,15,46,.95)',borderColor:'rgba(255,255,255,.06)',fontFamily:F.r}}>{options.map(o=><option key={o.v} value={o.v}>{o.l}</option>)}</select>;
const Md=({open,onClose,title,children}:{open:boolean;onClose:()=>void;title:string;children:ReactNode})=>{
if(!open)return null;
return<div className="fixed inset-0 z-50 flex items-end sm:items-center justify-center" onClick={onClose}><div className="absolute inset-0 bg-black/70 backdrop-blur-sm"/><div onClick={e=>e.stopPropagation()} className="relative w-full sm:max-w-md max-h-[85vh] overflow-y-auto rounded-t-2xl sm:rounded-2xl border" style={{background:'linear-gradient(180deg,#0c1133,#050816)',borderColor:`${C.c}15`}}><div className="sticky top-0 z-10 flex items-center justify-between p-4 border-b" style={{background:'rgba(5,8,22,.95)',borderColor:'rgba(255,255,255,.04)'}}><span className="text-sm font-bold tracking-wider" style={{fontFamily:F.o,color:C.c}}>{title}</span><button onClick={onClose} className="w-7 h-7 rounded-lg flex items-center justify-center text-gray-500" style={{background:'rgba(255,255,255,.04)'}}>✕</button></div><div className="p-4">{children}</div></div></div>;};
const PB=({val,max,color=C.c,h='h-1.5'}:{val:number;max:number;color?:string;h?:string})=>{
const p=max>0?Math.min((val/max)*100,100):0;
return<div className={`w-full ${h} rounded-full overflow-hidden`} style={{background:'rgba(255,255,255,.04)'}}><div className={`${h} rounded-full transition-all duration-700`} style={{width:`${p}%`,background:`linear-gradient(90deg,${color}80,${color})`,boxShadow:`0 0 6px ${color}40`}}/></div>;};
const SN=({value,label,color=C.c,icon=''}:{value:string|number;label:string;color?:string;icon?:string})=>
<div className="text-center">{icon&&<div className="text-lg mb-0.5">{icon}</div>}<div className="text-[15px] font-black" style={{fontFamily:F.o,color,textShadow:`0 0 8px ${color}30`}}>{typeof value==='number'?value.toLocaleString():value}</div><div className="text-[8px] tracking-[1.5px] mt-0.5" style={{fontFamily:F.r,color:'#475569'}}>{label}</div></div>;
const fmt=(s:number)=>{const h=Math.floor(s/3600),m=Math.floor((s%3600)/60),ss=s%60;return h>0?`${h}:${String(m).padStart(2,'0')}:${String(ss).padStart(2,'0')}`:`${String(m).padStart(2,'0')}:${String(ss).padStart(2,'0')}`;};

/* ═══ XP ENGINE ═══ */
function useXP(){
const[prof,setProf]=useState<Prof>(()=>ld('prof',defProf));
const[stats,setStats]=useState<Stats>(()=>ld('stats',defStats));
const[lvl,setLvl]=useState({show:false,level:0,rank:'',xp:0});
useEffect(()=>{sv('prof',prof)},[prof]);
useEffect(()=>{sv('stats',stats)},[stats]);
const addXP=useCallback((amt:number,b?:Partial<Stats>)=>{
setProf(p=>{let nx=p.xp+amt,nl=p.level,nxt=p.xpN,up=false;
while(nx>=nxt){nx-=nxt;nl++;nxt=Math.floor(nxt*1.12);up=true;}
const nr=getRank(nl);if(up)setLvl({show:true,level:nl,rank:nr,xp:amt});
return{...p,xp:nx,level:nl,xpN:nxt,totalXp:p.totalXp+amt,rank:nr,title:getTitle(nr),pwr:p.pwr+Math.floor(amt/5)};});
if(b)setStats(p=>{const n={...p};(Object.keys(b) as(keyof Stats)[]).forEach(k=>{n[k]=Math.min((n[k]||0)+(b[k]||0),999);});return n;});
},[]);
const doStreak=useCallback(()=>{setProf(p=>{const t=td();if(p.lastActive===t)return p;const y=new Date();y.setDate(y.getDate()-1);return{...p,streak:p.lastActive===y.toISOString().slice(0,10)?p.streak+1:1,lastActive:t};})},[]);
return{prof,setProf,stats,addXP,lvl,setLvl,doStreak};}

/* ═══ TIMER ═══ */
function useTimer(im:'sw'|'cd'='sw',id=1500){
const[mode,setMode]=useState(im);const[sec,setSec]=useState(im==='cd'?id:0);const[run,setRun]=useState(false);const[dur,setDur]=useState(id);
const ref=useRef<ReturnType<typeof setInterval>|null>(null);
useEffect(()=>{if(run){ref.current=setInterval(()=>{setSec(p=>{if(mode==='cd'&&p<=1){setRun(false);return 0;}return mode==='sw'?p+1:p-1;});},1000);}return()=>{if(ref.current)clearInterval(ref.current)};},[run,mode]);
const reset=useCallback(()=>{setRun(false);setSec(mode==='cd'?dur:0)},[mode,dur]);
const sw=useCallback((m:'sw'|'cd')=>{setMode(m);setRun(false);setSec(m==='cd'?dur:0)},[dur]);
const setCD=useCallback((d:number)=>{setDur(d);if(!run)setSec(d)},[run]);
return{sec,run,setRun,reset,mode,sw,setCD};}

/* ═══ LEVEL UP ═══ */
function LvlUp({d,onClose}:{d:{show:boolean;level:number;rank:string;xp:number};onClose:()=>void}){
useEffect(()=>{if(d.show){const t=setTimeout(onClose,3500);return()=>clearTimeout(t)}},[d.show,onClose]);
if(!d.show)return null;
return<div className="fixed inset-0 z-[100] flex items-center justify-center" onClick={onClose}><div className="absolute inset-0 bg-black/90 backdrop-blur-md"/><div className="relative z-10 text-center px-6"><GL cl="max-w-[180px] mx-auto mb-6"/><div className="text-[10px] tracking-[5px] mb-2" style={{fontFamily:F.r,color:'#475569'}}>QUEST COMPLETE</div><div className="text-4xl font-black mb-3" style={{fontFamily:F.o,background:`linear-gradient(135deg,${C.c},${C.p})`,WebkitBackgroundClip:'text',WebkitTextFillColor:'transparent',filter:`drop-shadow(0 0 16px ${C.c}60)`}}>+{d.xp} XP</div><div className="inline-block px-6 py-2.5 rounded-xl border mb-3" style={{background:`${C.c}08`,borderColor:`${C.c}30`,boxShadow:`0 0 30px ${C.c}12`}}><div className="text-[8px] tracking-[4px]" style={{fontFamily:F.r,color:`${C.c}70`}}>LEVEL UP</div><div className="text-3xl font-black" style={{fontFamily:F.o,color:C.c,textShadow:`0 0 16px ${C.c}60`}}>{d.level}</div></div><div className="text-sm font-bold tracking-wider" style={{fontFamily:F.r,color:RC[d.rank]||C.c}}>{d.rank}-RANK</div><GL color={C.p} cl="max-w-[180px] mx-auto mt-6"/></div></div>;}

/* ═══ HOME ═══ */
function Home({prof,stats,quests,achs,dl,setTab}:{prof:Prof;stats:Stats;quests:Quest[];achs:Ach[];dl:DL;setTab:(t:Tab)=>void}){
const rc=RC[prof.rank];const cq=quests.filter(q=>q.done).length;
return<div className="space-y-5">
<div className="text-center mb-2"><div className="inline-flex items-center gap-2 px-3 py-1 rounded-full border mb-2" style={{background:`${C.c}06`,borderColor:`${C.c}15`}}><div className="w-1.5 h-1.5 rounded-full animate-pulse" style={{background:C.c,boxShadow:`0 0 6px ${C.c}`}}/><span className="text-[8px] tracking-[3px] font-bold" style={{fontFamily:F.o,color:C.c}}>SYSTEM ONLINE</span></div><h1 className="text-xl font-black tracking-[3px]" style={{fontFamily:F.o,background:`linear-gradient(135deg,${C.c},${C.p})`,WebkitBackgroundClip:'text',WebkitTextFillColor:'transparent'}}>SHADOWFIT</h1><p className="text-[9px] tracking-[3px] mt-0.5" style={{fontFamily:F.r,color:'#334155'}}>{new Date().toLocaleDateString('en-US',{weekday:'long',month:'short',day:'numeric'}).toUpperCase()}</p></div>
<Cd glow={rc}><div className="flex items-center gap-4"><div className="w-14 h-14 rounded-full flex items-center justify-center text-xl font-bold border-2 flex-shrink-0" style={{background:'linear-gradient(135deg,#0a0f2e,#1a0a3e)',borderColor:rc,boxShadow:`0 0 20px ${rc}40`,fontFamily:F.o,color:rc}}>{prof.name[0]}</div><div className="flex-1 min-w-0"><div className="flex items-center gap-2 mb-0.5"><span className="text-sm font-bold text-white truncate" style={{fontFamily:F.o}}>{prof.name}</span><span className="px-1.5 py-0.5 rounded text-[9px] font-bold" style={{background:`${rc}18`,color:rc,border:`1px solid ${rc}40`,fontFamily:F.o}}>{prof.rank}</span></div><p className="text-[9px] tracking-[2px] mb-2" style={{fontFamily:F.r,color:`${C.c}70`}}>{prof.title.toUpperCase()}</p><div className="flex justify-between text-[8px] mb-1" style={{fontFamily:F.r,color:'#475569'}}><span>LVL {prof.level}</span><span>{prof.xp.toLocaleString()}/{prof.xpN.toLocaleString()} XP</span></div><PB val={prof.xp} max={prof.xpN}/></div></div><div className="grid grid-cols-3 gap-2 mt-3 pt-3 border-t" style={{borderColor:'rgba(255,255,255,.04)'}}><SN value={prof.pwr} label="POWER" color={C.c}/><SN value={`${prof.streak}🔥`} label="STREAK" color="#F59E0B"/><SN value={prof.totalXp} label="TOTAL XP" color={C.p}/></div></Cd>
<div className="grid grid-cols-3 gap-2">{[{i:'⚡',v:dl.xp,l:'XP TODAY',c:C.c},{i:'💪',v:`${dl.wMin}m`,l:'TRAINING',c:'#EF4444'},{i:'📚',v:`${dl.sMin}m`,l:'STUDY',c:'#10B981'}].map((s,i)=><Cd key={i} glow={s.c}><SN icon={s.i} value={s.v} label={s.l} color={s.c}/></Cd>)}</div>
<div><ST color="#F59E0B">⚔ DAILY QUESTS ({cq}/{quests.length})</ST>{quests.slice(0,4).map(q=><Cd key={q.id} glow={q.done?C.c:''} cl="mb-2"><div className="flex items-center gap-3"><div className="w-8 h-8 rounded-lg flex items-center justify-center text-[9px] font-bold border flex-shrink-0" style={{fontFamily:F.o,background:q.done?`${C.c}10`:`${C.p}08`,color:q.done?C.c:C.p,borderColor:q.done?`${C.c}30`:`${C.p}20`}}>{q.done?'✓':'!'}</div><div className="flex-1 min-w-0"><div className="flex items-center justify-between mb-1"><span className={`text-xs font-semibold truncate ${q.done?'line-through opacity-50':''}`} style={{fontFamily:F.r,color:q.done?C.c:'#e2e8f0'}}>{q.title}</span><span className="text-[8px] font-bold ml-2" style={{fontFamily:F.o,color:'#F59E0B'}}>+{q.xp}XP</span></div><PB val={q.current} max={q.target} color={q.done?C.c:C.p} h="h-1"/></div></div></Cd>)}</div>
<div><ST>⬡ ATTRIBUTES</ST><div className="grid grid-cols-4 gap-2">{(Object.entries(stats) as[keyof Stats,number][]).map(([k,v])=>{const cs:Record<string,string>={STR:'#EF4444',AGI:'#3B82F6',END:'#10B981',INT:'#8B5CF6',DIS:'#F59E0B',FOC:'#EC4899',KNW:'#06B6D4',CON:'#F97316'};const ic:Record<string,string>={STR:'⚔️',AGI:'💨',END:'🛡️',INT:'🧠',DIS:'🎯',FOC:'👁️',KNW:'📚',CON:'🔗'};return<Cd key={k} glow={cs[k]}><div className="text-center"><div className="text-sm">{ic[k]}</div><div className="text-xs font-black" style={{fontFamily:F.o,color:cs[k]}}>{v}</div><div className="text-[7px] tracking-[1px]" style={{fontFamily:F.o,color:`${cs[k]}80`}}>{k}</div></div></Cd>})}</div></div>
<div><ST color={C.p}>⚡ MODULES</ST><div className="grid grid-cols-4 gap-2">{[{id:'board' as Tab,i:'🎓',l:'BOARD',c:'#EC4899'},{id:'fit' as Tab,i:'💪',l:'FITNESS',c:'#EF4444'},{id:'study' as Tab,i:'📚',l:'STUDY',c:'#10B981'},{id:'exam' as Tab,i:'📝',l:'EXAM',c:'#8B5CF6'},{id:'cards' as Tab,i:'🃏',l:'CARDS',c:'#06B6D4'},{id:'code' as Tab,i:'💻',l:'CODE',c:'#3B82F6'},{id:'finance' as Tab,i:'💰',l:'FINANCE',c:'#F59E0B'},{id:'know' as Tab,i:'📖',l:'LEARN',c:'#F97316'}].map(m=><Cd key={m.id} glow={m.c} onClick={()=>setTab(m.id)}><div className="text-center"><div className="text-xl mb-0.5">{m.i}</div><div className="text-[7px] font-bold tracking-[1px]" style={{fontFamily:F.r,color:m.c}}>{m.l}</div></div></Cd>)}</div></div>
<div><ST color="#F59E0B">🏆 ACHIEVEMENTS</ST><div className="grid grid-cols-3 gap-2">{achs.slice(0,6).map(a=><Cd key={a.id} glow={a.earned?'#F59E0B':''}><div className="text-center"><div className="text-xl mb-0.5">{a.earned?a.icon:'🔒'}</div><div className="text-[8px] font-bold" style={{fontFamily:F.r,color:a.earned?'#e2e8f0':'#334155'}}>{a.title}</div><div className="text-[7px]" style={{color:a.earned?'#F59E0B':'#1e293b'}}>{a.tier}</div></div></Cd>)}</div></div>
<div className="text-[8px] text-center p-3 rounded-lg" style={{background:'rgba(255,255,255,.01)',color:'#334155',fontFamily:F.r}}>⚠️ Content for educational purposes. Verify important decisions with qualified professionals.</div>
</div>;}

/* ═══ FITNESS ═══ */
function Fit({addXP,workouts,setWorkouts,dl,setDL,weights,setWeights,water,setWater}:{addXP:(n:number,s?:Partial<Stats>)=>void;workouts:Workout[];setWorkouts:(w:Workout[])=>void;dl:DL;setDL:(d:DL)=>void;weights:WtEntry[];setWeights:(w:WtEntry[])=>void;water:WaterEntry[];setWater:(w:WaterEntry[])=>void}){
const[showAdd,setShowAdd]=useState(false);const[wN,setWN]=useState('');const[wT,setWT]=useState('strength');const[wD,setWD]=useState('30');const[wC,setWC]=useState('200');
const[exs,setExs]=useState<{name:string;sets:string;reps:string;wt:string}[]>([]);
const[view,setView]=useState<'main'|'calc'|'track'|'cali'>('main');
const[bmiW,setBmiW]=useState('');const[bmiH,setBmiH]=useState('');
const[wtIn,setWtIn]=useState('');
const timer=useTimer('sw');
const doAdd=()=>{if(!wN)return;const dur=parseInt(wD)||0,cal=parseInt(wC)||0,xp=Math.floor(dur*3+cal*.2);const w:Workout={id:uid(),name:wN,type:wT,dur,cal,exs:exs.map(e=>({name:e.name,sets:parseInt(e.sets)||0,reps:parseInt(e.reps)||0,wt:parseInt(e.wt)||0})),date:td(),xp};const nw=[w,...workouts];setWorkouts(nw);sv('workouts',nw);addXP(xp,{STR:wT==='strength'?3:1,END:wT==='cardio'?3:1,AGI:wT==='hiit'?2:1});setDL({...dl,xp:dl.xp+xp,wMin:dl.wMin+dur});setShowAdd(false);setWN('');setExs([])};
const qLog=(n:string,t:string,d:number,c:number,xp:number)=>{const w:Workout={id:uid(),name:n,type:t,dur:d,cal:c,exs:[],date:td(),xp};const nw=[w,...workouts];setWorkouts(nw);sv('workouts',nw);addXP(xp,{STR:2,END:1});setDL({...dl,xp:dl.xp+xp,wMin:dl.wMin+d})};
const bmi=bmiW&&bmiH?parseFloat(bmiW)/(parseFloat(bmiH)/100)**2:0;
const addWt=()=>{if(!wtIn)return;const e:WtEntry={id:uid(),kg:parseFloat(wtIn),date:td()};const nw=[e,...weights];setWeights(nw);sv('weights',nw);setWtIn('')};
const addWater=(ml:number)=>{const t=td();const ex=water.find(w=>w.date===t);const nw=ex?water.map(w=>w.date===t?{...w,ml:w.ml+ml}:w):[...water,{date:t,ml}];setWater(nw);sv('water',nw)};
const todayWater=water.find(w=>w.date===td())?.ml||0;
return<div className="space-y-5">
<ST color="#EF4444">💪 FITNESS SYSTEM</ST>
<div className="flex gap-2 flex-wrap">{(['main','calc','track','cali'] as const).map(v=><Bt key={v} sm color="#EF4444" v={view===v?'solid':'outline'} onClick={()=>setView(v)}>{v==='main'?'WORKOUT':v==='calc'?'CALCULATORS':v==='track'?'TRACKERS':'CALISTHENICS'}</Bt>)}</div>
{view==='main'&&<>
<Cd glow="#EF4444"><div className="text-center"><div className="flex justify-center gap-2 mb-3"><Bt sm color="#EF4444" v={timer.mode==='sw'?'solid':'outline'} onClick={()=>timer.sw('sw')}>STOPWATCH</Bt><Bt sm color="#EF4444" v={timer.mode==='cd'?'solid':'outline'} onClick={()=>timer.sw('cd')}>COUNTDOWN</Bt></div>{timer.mode==='cd'&&!timer.run&&<div className="flex justify-center gap-2 mb-3 flex-wrap">{[60,180,300,600,900,1800].map(s=><Bt key={s} sm v="ghost" color="#EF4444" onClick={()=>timer.setCD(s)}>{s<60?`${s}s`:`${Math.floor(s/60)}m`}</Bt>)}</div>}<div className="text-4xl font-black mb-4" style={{fontFamily:F.m,color:'#EF4444',textShadow:'0 0 20px rgba(239,68,68,.3)'}}>{fmt(timer.sec)}</div><div className="flex justify-center gap-3"><Bt color="#EF4444" onClick={()=>timer.setRun(!timer.run)}>{timer.run?'⏸ PAUSE':'▶ START'}</Bt><Bt color="#EF4444" v="outline" onClick={timer.reset}>↺ RESET</Bt></div></div></Cd>
<div className="grid grid-cols-3 gap-2">{[{n:'Push-ups',t:'strength',d:15,c:100,xp:55},{n:'Running',t:'cardio',d:30,c:300,xp:120},{n:'Yoga',t:'flexibility',d:20,c:100,xp:70},{n:'HIIT',t:'hiit',d:20,c:250,xp:100},{n:'Walking',t:'cardio',d:30,c:150,xp:60},{n:'Swimming',t:'cardio',d:30,c:350,xp:130}].map(q=><Cd key={q.n} glow="#EF4444" onClick={()=>qLog(q.n,q.t,q.d,q.c,q.xp)}><div className="text-center"><div className="text-[9px] font-bold" style={{fontFamily:F.r,color:'#EF4444'}}>{q.n.toUpperCase()}</div><div className="text-[8px]" style={{color:'#475569'}}>+{q.xp} XP</div></div></Cd>)}</div>
<Bt color="#EF4444" cl="w-full" onClick={()=>setShowAdd(true)}>+ LOG CUSTOM WORKOUT</Bt>
<div className="grid grid-cols-2 gap-2"><Cd glow="#EF4444"><SN icon="🔥" value={workouts.filter(w=>w.date===td()).reduce((a,b)=>a+b.cal,0)} label="CALORIES" color="#EF4444"/></Cd><Cd glow="#F59E0B"><SN icon="⏱" value={`${workouts.filter(w=>w.date===td()).reduce((a,b)=>a+b.dur,0)}m`} label="TIME" color="#F59E0B"/></Cd></div>
<ST color="#EF4444">📋 HISTORY</ST>{workouts.slice(0,6).map(w=><Cd key={w.id} cl="mb-2"><div className="flex items-center justify-between"><div><div className="text-sm font-bold" style={{fontFamily:F.r}}>{w.name}</div><div className="text-[10px]" style={{color:'#475569'}}>{w.type}·{w.dur}m·{w.cal}cal</div></div><div className="text-xs font-bold" style={{fontFamily:F.o,color:'#EF4444'}}>+{w.xp}XP</div></div></Cd>)}
</>}
{view==='calc'&&<>
<Cd glow="#F59E0B"><div className="text-[10px] tracking-[2px] font-bold mb-3" style={{fontFamily:F.o,color:'#F59E0B'}}>BMI CALCULATOR</div><div className="grid grid-cols-2 gap-2 mb-3"><In type="number" value={bmiW} onChange={setBmiW} placeholder="Weight (kg)"/><In type="number" value={bmiH} onChange={setBmiH} placeholder="Height (cm)"/></div>{bmi>0&&<div className="text-center"><div className="text-2xl font-black" style={{fontFamily:F.o,color:bmi<18.5?'#3B82F6':bmi<25?'#10B981':bmi<30?'#F59E0B':'#EF4444'}}>{bmi.toFixed(1)}</div><div className="text-xs" style={{color:'#94A3B8'}}>{bmi<18.5?'Underweight':bmi<25?'Normal':bmi<30?'Overweight':'Obese'}</div></div>}</Cd>
<Cd glow="#06B6D4"><div className="text-[10px] tracking-[2px] font-bold mb-3" style={{fontFamily:F.o,color:'#06B6D4'}}>WATER INTAKE CALC</div><div className="text-center"><div className="text-xs mb-1" style={{color:'#94A3B8'}}>Recommended: {bmiW?Math.round(parseFloat(bmiW)*35):2500}ml/day</div>{bmiW&&<div className="text-lg font-black" style={{fontFamily:F.o,color:'#06B6D4'}}>{Math.round(parseFloat(bmiW)*35)}ml</div>}</div></Cd>
<Cd glow="#EC4899"><div className="text-[10px] tracking-[2px] font-bold mb-3" style={{fontFamily:F.o,color:'#EC4899'}}>CALORIE CALCULATOR</div><div className="text-xs" style={{color:'#94A3B8'}}>BMR (Mifflin): {bmiW&&bmiH?Math.round(10*parseFloat(bmiW)+6.25*parseFloat(bmiH)-5*25+5):'-'} cal/day<br/>Maintenance (×1.55): {bmiW&&bmiH?Math.round((10*parseFloat(bmiW)+6.25*parseFloat(bmiH)-5*25+5)*1.55):'-'} cal/day</div></Cd>
</>}
{view==='track'&&<>
<Cd glow="#3B82F6"><div className="text-[10px] tracking-[2px] font-bold mb-3" style={{fontFamily:F.o,color:'#3B82F6'}}>WEIGHT TRACKER</div><div className="flex gap-2"><In type="number" value={wtIn} onChange={setWtIn} placeholder="Weight (kg)"/><Bt color="#3B82F6" onClick={addWt}>LOG</Bt></div>{weights.slice(0,5).map(w=><div key={w.id} className="flex justify-between py-1.5 border-t first:border-0 text-xs" style={{borderColor:'rgba(255,255,255,.04)'}}><span>{w.date}</span><span style={{color:'#3B82F6',fontFamily:F.o}}>{w.kg}kg</span></div>)}</Cd>
<Cd glow="#06B6D4"><div className="text-[10px] tracking-[2px] font-bold mb-3" style={{fontFamily:F.o,color:'#06B6D4'}}>💧 WATER ({todayWater}ml / 3000ml)</div><PB val={todayWater} max={3000} color="#06B6D4"/><div className="flex gap-2 mt-3">{[250,500,750].map(ml=><Bt key={ml} sm color="#06B6D4" v="outline" onClick={()=>addWater(ml)}>+{ml}ml</Bt>)}</div></Cd>
</>}
{view==='cali'&&<>
<ST color="#EF4444">🤸 CALISTHENICS</ST>
{['Push-ups','Pull-ups','Dips','Handstand','Muscle-up','Front Lever','Planche','Human Flag','L-Sit','Pistol Squat'].map(ex=><Cd key={ex} glow="#EF4444" cl="mb-2" onClick={()=>qLog(ex,'calisthenics',10,80,40)}><div className="flex items-center justify-between"><span className="text-sm font-bold" style={{fontFamily:F.r}}>{ex}</span><span className="text-[9px]" style={{color:'#EF4444'}}>+40 XP</span></div></Cd>)}
</>}
<Md open={showAdd} onClose={()=>setShowAdd(false)} title="LOG WORKOUT"><div className="space-y-3"><In value={wN} onChange={setWN} placeholder="Workout name"/><Sl value={wT} onChange={setWT} options={[{v:'strength',l:'Strength'},{v:'cardio',l:'Cardio'},{v:'hiit',l:'HIIT'},{v:'flexibility',l:'Flexibility'},{v:'calisthenics',l:'Calisthenics'},{v:'sports',l:'Sports'}]}/><div className="grid grid-cols-2 gap-3"><In type="number" value={wD} onChange={setWD} placeholder="Duration"/><In type="number" value={wC} onChange={setWC} placeholder="Calories"/></div>{exs.map((e,i)=><Cd key={i}><div className="space-y-2"><In value={e.name} onChange={v=>{const n=[...exs];n[i].name=v;setExs(n)}} placeholder="Exercise"/><div className="grid grid-cols-3 gap-2"><In type="number" value={e.sets} onChange={v=>{const n=[...exs];n[i].sets=v;setExs(n)}} placeholder="Sets"/><In type="number" value={e.reps} onChange={v=>{const n=[...exs];n[i].reps=v;setExs(n)}} placeholder="Reps"/><In type="number" value={e.wt} onChange={v=>{const n=[...exs];n[i].wt=v;setExs(n)}} placeholder="kg"/></div></div></Cd>)}<Bt color="#EF4444" v="outline" cl="w-full" onClick={()=>setExs([...exs,{name:'',sets:'3',reps:'10',wt:'0'}])}>+ EXERCISE</Bt><Bt color="#EF4444" cl="w-full" onClick={doAdd}>COMPLETE</Bt></div></Md>
</div>;}

/* ═══ STUDY ═══ */
function Study({addXP,ses,setSes,notes,setNotes,dl,setDL}:{addXP:(n:number,s?:Partial<Stats>)=>void;ses:StudySes[];setSes:(s:StudySes[])=>void;notes:Note[];setNotes:(n:Note[])=>void;dl:DL;setDL:(d:DL)=>void}){
const[sub,setSub]=useState('');const[pa,setPa]=useState(false);const[pc,setPc]=useState(0);const[showN,setShowN]=useState(false);const[nT,setNT]=useState('');const[nB,setNB]=useState('');const[nS,setNS]=useState('General');
const timer=useTimer('cd',1500);
const finPom=useCallback(()=>{const xp=50;const s:StudySes={id:uid(),sub:sub||'General',dur:25,type:'pomodoro',date:td(),xp};const ns=[s,...ses];setSes(ns);sv('study_ses',ns);addXP(xp,{INT:2,FOC:2,KNW:1,DIS:1});setDL({...dl,xp:dl.xp+xp,sMin:dl.sMin+25});setPc(p=>p+1);setPa(false)},[sub,ses,setSes,addXP,dl,setDL]);
useEffect(()=>{if(timer.mode==='cd'&&timer.sec===0&&pa)finPom()},[timer.sec,pa,finPom]);
const startPom=()=>{timer.sw('cd');timer.setCD(1500);timer.setRun(true);setPa(true)};
const logS=(d:number,xp:number)=>{const s:StudySes={id:uid(),sub:sub||'General',dur:d,type:'manual',date:td(),xp};const ns=[s,...ses];setSes(ns);sv('study_ses',ns);addXP(xp,{INT:2,KNW:1,FOC:1});setDL({...dl,xp:dl.xp+xp,sMin:dl.sMin+d})};
const saveN=()=>{if(!nT)return;const n:Note={id:uid(),title:nT,body:nB,sub:nS,date:td()};const nn=[n,...notes];setNotes(nn);sv('notes',nn);addXP(15,{KNW:1,INT:1});setShowN(false);setNT('');setNB('')};
return<div className="space-y-5">
<ST color="#10B981">📚 STUDY HUB</ST>
<Cd glow="#10B981"><div className="text-center"><div className="text-[10px] tracking-[3px] mb-2 font-bold" style={{fontFamily:F.o,color:'#10B981'}}>POMODORO TIMER</div><In value={sub} onChange={setSub} placeholder="Subject" cl="mb-3"/><div className="text-4xl font-black mb-4" style={{fontFamily:F.m,color:'#10B981',textShadow:'0 0 20px rgba(16,185,129,.3)'}}>{fmt(timer.sec)}</div><div className="flex justify-center gap-3 mb-3">{!pa?<Bt color="#10B981" onClick={startPom}>▶ START FOCUS</Bt>:<><Bt color="#10B981" onClick={()=>timer.setRun(!timer.run)}>{timer.run?'⏸':'▶'}</Bt><Bt color="#10B981" v="outline" onClick={()=>{timer.reset();setPa(false)}}>CANCEL</Bt></>}</div><div className="flex justify-center gap-1">{[...Array(4)].map((_,i)=><div key={i} className="w-3 h-3 rounded-full" style={{background:i<pc?'#10B981':'rgba(255,255,255,.06)'}}/>)}</div></div></Cd>
<div className="grid grid-cols-4 gap-2">{[{d:15,xp:25},{d:30,xp:50},{d:60,xp:110},{d:120,xp:230}].map(q=><Cd key={q.d} glow="#10B981" onClick={()=>logS(q.d,q.xp)}><div className="text-center"><div className="text-xs font-bold" style={{fontFamily:F.o,color:'#10B981'}}>{q.d}m</div><div className="text-[8px]" style={{color:'#475569'}}>+{q.xp}XP</div></div></Cd>)}</div>
<Bt color="#06B6D4" cl="w-full" onClick={()=>setShowN(true)}>📝 NEW NOTE</Bt>
{notes.slice(0,4).map(n=><Cd key={n.id} cl="mb-2"><div className="text-sm font-bold" style={{fontFamily:F.r}}>{n.title}</div><div className="text-[10px] mt-0.5 lc2" style={{color:'#94A3B8'}}>{n.body}</div><div className="text-[9px] mt-0.5" style={{color:'#475569'}}>{n.sub}·{n.date}</div></Cd>)}
<ST color="#10B981">📋 LOG</ST>{ses.slice(0,6).map(s=><Cd key={s.id} cl="mb-2"><div className="flex items-center justify-between"><div><div className="text-sm font-bold" style={{fontFamily:F.r}}>{s.sub}</div><div className="text-[10px]" style={{color:'#475569'}}>{s.type}·{s.dur}m</div></div><div className="text-xs font-bold" style={{fontFamily:F.o,color:'#10B981'}}>+{s.xp}XP</div></div></Cd>)}
<Md open={showN} onClose={()=>setShowN(false)} title="NEW NOTE"><div className="space-y-3"><In value={nT} onChange={setNT} placeholder="Title"/><In value={nS} onChange={setNS} placeholder="Subject"/><textarea value={nB} onChange={e=>setNB(e.target.value)} placeholder="Write notes..." className="w-full px-3 py-2.5 rounded-lg text-sm text-white placeholder:text-gray-600 outline-none border h-40 resize-none" style={{background:'rgba(255,255,255,.03)',borderColor:'rgba(255,255,255,.06)',fontFamily:F.r}}/><Bt color="#06B6D4" cl="w-full" onClick={saveN}>SAVE (+15 XP)</Bt></div></Md>
</div>;}

/* ═══ BOARD 12 ═══ */
function Board({addXP,prof,qr,setQR,dl,setDL}:{addXP:(n:number,s?:Partial<Stats>)=>void;prof:Prof;qr:QR[];setQR:(r:QR[])=>void;dl:DL;setDL:(d:DL)=>void}){
const[view,setView]=useState<'home'|'sub'|'ch'|'cfg'|'quiz'|'result'|'ana'>('home');
const[stream,setStream]=useState(prof.stream||'Science');const[selSub,setSelSub]=useState('');const[selCh,setSelCh]=useState('');const[qType,setQType]=useState('');
const[qs,setQs]=useState<B12Question[]>([]);const[cur,setCur]=useState(0);const[sel,setSel]=useState<number|null>(null);const[showE,setShowE]=useState(false);const[score,setScore]=useState(0);
const subs=getSubjectsForStream(stream);const subObj=subs.find(s=>s.id===selSub);const chapObj=subObj?.chapters.find(c=>c.id===selCh);
const examDate=new Date(new Date().getFullYear(),2,1);if(examDate<new Date())examDate.setFullYear(examDate.getFullYear()+1);
const daysLeft=Math.max(0,Math.ceil((examDate.getTime()-Date.now())/86400000));
const startQ=(count:number)=>{const q=getB12Questions(subObj?.name||'',chapObj?.name,qType||undefined,count);if(!q.length)return;setQs(q);setCur(0);setSel(null);setShowE(false);setScore(0);setView('quiz')};
const pick=(i:number)=>{if(showE)return;setSel(i);setShowE(true);if(i===qs[cur].correct)setScore(s=>s+1)};
const next=()=>{if(cur+1>=qs.length){const xp=Math.floor(score*(score/qs.length>=.9?40:30));const r:QR={id:uid(),sub:subObj?.name||'',ch:chapObj?.name||'Full',sc:score,tot:qs.length,date:td(),mode:'board',xp,diff:''};const nr=[r,...qr];setQR(nr);sv('qr',nr);addXP(xp,{INT:3,KNW:2,DIS:1});setDL({...dl,xp:dl.xp+xp,sMin:dl.sMin+5});setView('result')}else{setCur(c=>c+1);setSel(null);setShowE(false)}};
const subScores=subs.map(s=>{const rs=qr.filter(r=>r.sub===s.name);const tot=rs.reduce((a,b)=>a+b.tot,0);const sc=rs.reduce((a,b)=>a+b.sc,0);return{name:s.name,icon:s.icon,color:s.color,tests:rs.length,acc:tot>0?Math.round(sc/tot*100):0}});
return<div className="space-y-5">
{view==='home'&&<><ST color="#EC4899">🎓 CLASS 12 BOARD</ST><Cd glow="#EC4899"><div className="text-center"><div className="text-[9px] tracking-[3px] mb-1 font-bold" style={{fontFamily:F.o,color:'#EC4899'}}>EXAM COUNTDOWN</div><div className="text-3xl font-black" style={{fontFamily:F.o,color:C.c,textShadow:`0 0 12px ${C.c}40`}}>{daysLeft}</div><div className="text-[9px] tracking-[2px]" style={{fontFamily:F.r,color:'#475569'}}>DAYS LEFT</div></div></Cd><div className="flex gap-2">{['Science','Commerce','Arts'].map(s=><Bt key={s} sm color="#EC4899" v={stream===s?'solid':'outline'} onClick={()=>{setStream(s);setSelSub('')}}>{s.toUpperCase()}</Bt>)}</div><div className="grid grid-cols-2 gap-2">{subs.map(s=><Cd key={s.id} glow={s.color} onClick={()=>{setSelSub(s.id);setView('sub')}}><div className="flex items-center gap-3"><div className="text-2xl">{s.icon}</div><div><div className="text-xs font-bold" style={{fontFamily:F.r,color:s.color}}>{s.name.toUpperCase()}</div><div className="text-[9px]" style={{color:'#475569'}}>{s.chapters.length} ch</div></div></div></Cd>)}</div><Bt color="#EC4899" v="outline" cl="w-full" onClick={()=>setView('ana')}>📊 ANALYTICS</Bt></>}
{view==='sub'&&subObj&&<><Bt sm v="ghost" color={C.c} onClick={()=>setView('home')} cl="mb-2">← BACK</Bt><ST color={subObj.color}>{subObj.icon} {subObj.name.toUpperCase()}</ST><div className="grid grid-cols-2 gap-2 mb-3">{[{l:'Chapter Test',c:5},{l:'Full Subject',c:10},{l:'Mock Board',c:15},{l:'Quick 5',c:5}].map(x=><Cd key={x.l} glow={subObj.color} onClick={()=>{setSelCh('');setView('cfg')}}><div className="text-center text-[9px] font-bold" style={{fontFamily:F.r,color:subObj.color}}>{x.l.toUpperCase()}</div></Cd>)}</div>{subObj.chapters.map(ch=><Cd key={ch.id} glow={subObj.color} cl="mb-2" onClick={()=>{setSelCh(ch.id);setView('ch')}}><div className="flex items-center justify-between"><div className="text-sm font-bold" style={{fontFamily:F.r}}>{ch.name}</div><div className="flex gap-1">{ch.quickNotes&&<span className="text-[7px] px-1 py-0.5 rounded" style={{background:`${subObj.color}12`,color:subObj.color}}>Notes</span>}{ch.formulaSheet&&<span className="text-[7px] px-1 py-0.5 rounded" style={{background:'rgba(245,158,11,.1)',color:'#F59E0B'}}>F</span>}</div></div></Cd>)}</>}
{view==='ch'&&subObj&&chapObj&&<><Bt sm v="ghost" color={C.c} onClick={()=>setView('sub')} cl="mb-2">← BACK</Bt><ST color={subObj.color}>{chapObj.name.toUpperCase()}</ST><Cd glow={subObj.color} cl="mb-3"><div className="text-[10px] tracking-[2px] font-bold mb-2" style={{fontFamily:F.o,color:subObj.color}}>TOPICS</div>{chapObj.topics.map((t,i)=><div key={i} className="text-sm py-1.5 border-t first:border-0" style={{borderColor:'rgba(255,255,255,.04)',fontFamily:F.r}}>• {t}</div>)}</Cd>{chapObj.quickNotes&&<Cd glow="#10B981" cl="mb-3"><div className="text-[10px] tracking-[2px] font-bold mb-2" style={{fontFamily:F.o,color:'#10B981'}}>📝 NOTES</div>{chapObj.quickNotes.map((n,i)=><div key={i} className="text-sm py-1 text-gray-400" style={{fontFamily:F.r}}>• {n}</div>)}</Cd>}{chapObj.formulaSheet&&<Cd glow="#F59E0B" cl="mb-3"><div className="text-[10px] tracking-[2px] font-bold mb-2" style={{fontFamily:F.o,color:'#F59E0B'}}>📐 FORMULAS</div>{chapObj.formulaSheet.map((f,i)=><div key={i} className="text-sm py-1 text-gray-400" style={{fontFamily:F.m,fontSize:'12px'}}>{f}</div>)}</Cd>}<Bt color={subObj.color} cl="w-full" onClick={()=>setView('cfg')}>📝 TEST THIS CHAPTER</Bt></>}
{view==='cfg'&&<Cd glow="#EC4899"><div className="space-y-3"><div className="text-[10px] tracking-[2px] font-bold" style={{fontFamily:F.o,color:'#EC4899'}}>TEST CONFIG</div><div className="flex gap-2 flex-wrap">{['','mcq','assertion','case','numerical'].map(t=><Bt key={t} sm color="#EC4899" v={qType===t?'solid':'outline'} onClick={()=>setQType(t)}>{t||'ALL'}</Bt>)}</div><div className="flex gap-2"><Bt color="#94A3B8" v="outline" onClick={()=>setView(selCh?'ch':'sub')}>BACK</Bt><Bt color="#EC4899" cl="flex-1" onClick={()=>startQ(chapObj?5:10)}>START</Bt></div></div></Cd>}
{view==='quiz'&&qs.length>0&&<Cd glow="#EC4899"><div className="mb-4"><div className="flex items-center justify-between mb-2"><span className="text-[9px] font-bold" style={{fontFamily:F.o,color:'#EC4899'}}>{cur+1}/{qs.length}</span></div><PB val={cur+1} max={qs.length} color="#EC4899" h="h-1"/></div><div className="text-sm font-bold mb-4 whitespace-pre-line" style={{fontFamily:F.r,lineHeight:'1.6'}}>{qs[cur].question}</div><div className="space-y-2">{qs[cur].options.map((o,i)=>{let bg='rgba(255,255,255,.03)',bd='rgba(255,255,255,.06)',cl='#e2e8f0';if(showE){if(i===qs[cur].correct){bg='rgba(16,185,129,.12)';bd='#10B981';cl='#10B981'}else if(i===sel&&i!==qs[cur].correct){bg='rgba(239,68,68,.12)';bd='#EF4444';cl='#EF4444'}}else if(i===sel){bg=`${C.c}12`;bd=C.c;cl=C.c}return<button key={i} onClick={()=>pick(i)} className="w-full text-left px-4 py-3 rounded-lg border text-sm font-semibold active:scale-[.98]" style={{background:bg,borderColor:bd,color:cl,fontFamily:F.r}}>{String.fromCharCode(65+i)}. {o}</button>})}</div>{showE&&<div className="mt-3 p-3 rounded-lg border" style={{background:'rgba(139,92,246,.06)',borderColor:'rgba(139,92,246,.15)'}}><div className="text-xs" style={{color:'#94A3B8'}}>{qs[cur].explanation}</div></div>}{showE&&<Bt color="#EC4899" cl="w-full mt-3" onClick={next}>{cur+1>=qs.length?'RESULTS':'NEXT →'}</Bt>}</Cd>}
{view==='result'&&<Cd glow={score/qs.length>=.9?'#10B981':'#F59E0B'}><div className="text-center py-4"><div className="text-4xl mb-2">{score/qs.length>=.9?'🏆':'⭐'}</div><div className="text-3xl font-black" style={{fontFamily:F.o,color:C.c}}>{score}/{qs.length}</div><div className="text-lg font-bold" style={{fontFamily:F.o,color:'#F59E0B'}}>+{Math.floor(score*(score/qs.length>=.9?40:30))} XP</div><Bt color="#EC4899" cl="mt-4" onClick={()=>setView('home')}>BACK</Bt></div></Cd>}
{view==='ana'&&<><Bt sm v="ghost" color={C.c} onClick={()=>setView('home')} cl="mb-2">← BACK</Bt><ST color="#EC4899">📊 ANALYTICS</ST>{subScores.map(s=><Cd key={s.name} glow={s.color} cl="mb-2"><div className="flex items-center gap-3"><span className="text-xl">{s.icon}</span><div className="flex-1"><div className="text-sm font-bold" style={{fontFamily:F.r,color:s.color}}>{s.name}</div><PB val={s.acc} max={100} color={s.color} h="h-1"/></div><div className="text-sm font-black" style={{fontFamily:F.o,color:s.acc>=80?'#10B981':s.acc>0?'#F59E0B':'#475569'}}>{s.acc}%</div></div></Cd>)}</>}
</div>;}

/* ═══ EXAM ═══ */
function Exam({addXP,prof,qr,setQR}:{addXP:(n:number,s?:Partial<Stats>)=>void;prof:Prof;qr:QR[];setQR:(r:QR[])=>void}){
const[mode,setMode]=useState<'menu'|'cfg'|'quiz'|'result'>('menu');const[sub,setSub]=useState('Mathematics');const[diff,setDiff]=useState('medium');
const[qs,setQs]=useState<{id:string;question:string;options:string[];correct:number;explanation:string;difficulty:string}[]>([]);const[cur,setCur]=useState(0);const[sel,setSel]=useState<number|null>(null);const[showE,setShowE]=useState(false);const[score,setScore]=useState(0);
const subs=[...new Set(getQuestions({count:999}).map(q=>q.subject))];
const start=()=>{const q=getQuestions({subject:sub,difficulty:diff,classLevel:prof.cls,count:10});if(!q.length)return;setQs(q);setCur(0);setSel(null);setShowE(false);setScore(0);setMode('quiz')};
const pick=(i:number)=>{if(showE)return;setSel(i);setShowE(true);if(i===qs[cur].correct)setScore(s=>s+1)};
const next=()=>{if(cur+1>=qs.length){const xp=score*30;const r:QR={id:uid(),sub,ch:'',sc:score,tot:qs.length,date:td(),mode:'exam',xp,diff};const nr=[r,...qr];setQR(nr);sv('qr',nr);addXP(xp,{INT:2,KNW:3});setMode('result')}else{setCur(c=>c+1);setSel(null);setShowE(false)}};
return<div className="space-y-5">
<ST color="#8B5CF6">📝 EXAM SYSTEM</ST>
{mode==='menu'&&<><div className="grid grid-cols-2 gap-2">{subs.map(s=><Cd key={s} glow="#8B5CF6" onClick={()=>{setSub(s);setMode('cfg')}}><div className="text-center text-[10px] font-bold" style={{fontFamily:F.r,color:'#8B5CF6'}}>{s.toUpperCase()}</div></Cd>)}</div><ST color="#8B5CF6">📊 RESULTS</ST>{qr.filter(r=>r.mode==='exam').slice(0,5).map(r=><Cd key={r.id} cl="mb-2"><div className="flex justify-between"><div className="text-sm font-bold" style={{fontFamily:F.r}}>{r.sub}</div><div className="text-xs font-bold" style={{fontFamily:F.o,color:r.sc/r.tot>=.8?'#10B981':'#F59E0B'}}>{r.sc}/{r.tot}</div></div></Cd>)}</>}
{mode==='cfg'&&<Cd glow="#8B5CF6"><div className="space-y-3"><div className="text-sm font-bold" style={{fontFamily:F.o,color:'#8B5CF6'}}>{sub}</div><div className="flex gap-2">{['easy','medium','hard'].map(d=><Bt key={d} sm color="#8B5CF6" v={diff===d?'solid':'outline'} onClick={()=>setDiff(d)}>{d.toUpperCase()}</Bt>)}</div><div className="flex gap-2"><Bt color="#94A3B8" v="outline" onClick={()=>setMode('menu')}>BACK</Bt><Bt color="#8B5CF6" cl="flex-1" onClick={start}>START</Bt></div></div></Cd>}
{mode==='quiz'&&qs.length>0&&<Cd glow="#8B5CF6"><PB val={cur+1} max={qs.length} color="#8B5CF6" h="h-1"/><div className="text-sm font-bold mt-3 mb-4" style={{fontFamily:F.r}}>{qs[cur].question}</div><div className="space-y-2">{qs[cur].options.map((o,i)=>{let bg='rgba(255,255,255,.03)',bd='rgba(255,255,255,.06)',cl='#e2e8f0';if(showE){if(i===qs[cur].correct){bg='rgba(16,185,129,.12)';bd='#10B981';cl='#10B981'}else if(i===sel){bg='rgba(239,68,68,.12)';bd='#EF4444';cl='#EF4444'}}else if(i===sel){bg=`${C.c}12`;bd=C.c;cl=C.c}return<button key={i} onClick={()=>pick(i)} className="w-full text-left px-4 py-3 rounded-lg border text-sm active:scale-[.98]" style={{background:bg,borderColor:bd,color:cl,fontFamily:F.r}}>{String.fromCharCode(65+i)}. {o}</button>})}</div>{showE&&<><div className="mt-3 p-3 rounded-lg text-xs" style={{background:'rgba(139,92,246,.06)',color:'#94A3B8'}}>{qs[cur].explanation}</div><Bt color="#8B5CF6" cl="w-full mt-3" onClick={next}>{cur+1>=qs.length?'RESULTS':'NEXT →'}</Bt></>}</Cd>}
{mode==='result'&&<Cd glow="#10B981"><div className="text-center py-4"><div className="text-3xl font-black" style={{fontFamily:F.o,color:C.c}}>{score}/{qs.length}</div><div className="text-lg font-bold" style={{fontFamily:F.o,color:'#F59E0B'}}>+{score*30} XP</div><Bt color="#8B5CF6" cl="mt-4" onClick={()=>setMode('menu')}>BACK</Bt></div></Cd>}
</div>;}

/* ═══ FLASHCARDS ═══ */
function Cards({addXP,fcs,setFCs}:{addXP:(n:number,s?:Partial<Stats>)=>void;fcs:FC[];setFCs:(f:FC[])=>void}){
const[showA,setShowA]=useState(false);const[fr,setFr]=useState('');const[bk,setBk]=useState('');const[sub,setSub]=useState('');
const[ri,setRi]=useState(0);const[fl,setFl]=useState(false);const[rev,setRev]=useState(false);
const due=fcs.filter(f=>f.next<=td());
const add=()=>{if(!fr||!bk)return;const f:FC={id:uid(),front:fr,back:bk,sub:sub||'General',next:td(),iv:1,ease:2.5};const nf=[...fcs,f];setFCs(nf);sv('fcs',nf);setFr('');setBk('');addXP(10,{KNW:1})};
const review=(q:number)=>{const c=due[ri];let ni=c.iv,ne=c.ease;if(q>=3){ni=Math.round(ni*ne);ne=Math.max(1.3,ne+0.1*(q-3))}else{ni=1;ne=Math.max(1.3,ne-0.2)}const nd=new Date();nd.setDate(nd.getDate()+ni);const nf=fcs.map(f=>f.id===c.id?{...f,iv:ni,ease:ne,next:nd.toISOString().slice(0,10)}:f);setFCs(nf);sv('fcs',nf);addXP(q>=3?15:5,{KNW:1,INT:1});if(ri+1>=due.length){setRev(false);setRi(0)}else{setRi(r=>r+1);setFl(false)}};
return<div className="space-y-5">
<ST color="#06B6D4">🃏 FLASHCARDS</ST>
<div className="grid grid-cols-2 gap-2"><Cd glow="#06B6D4"><SN icon="📚" value={fcs.length} label="TOTAL" color="#06B6D4"/></Cd><Cd glow={due.length>0?'#F59E0B':'#10B981'}><SN icon="📋" value={due.length} label="DUE" color={due.length>0?'#F59E0B':'#10B981'}/></Cd></div>
{!rev?<>{due.length>0&&<Bt color="#06B6D4" cl="w-full" onClick={()=>{setRev(true);setRi(0);setFl(false)}}>▶ REVIEW {due.length} CARDS</Bt>}<Bt color="#06B6D4" v="outline" cl="w-full" onClick={()=>setShowA(true)}>+ ADD CARD</Bt>{fcs.slice(0,8).map(f=><Cd key={f.id} cl="mb-2"><div className="text-sm font-bold" style={{fontFamily:F.r}}>{f.front}</div><div className="text-[10px]" style={{color:'#94A3B8'}}>{f.back}</div></Cd>)}</>
:<Cd glow="#06B6D4"><div className="text-center"><div className="text-[9px] font-bold mb-3" style={{fontFamily:F.o,color:'#06B6D4'}}>REVIEW {ri+1}/{due.length}</div><div onClick={()=>setFl(!fl)} className="min-h-[100px] flex items-center justify-center p-4 rounded-xl border mb-4 cursor-pointer" style={{background:fl?'rgba(6,182,212,.06)':'rgba(255,255,255,.02)',borderColor:fl?'rgba(6,182,212,.2)':'rgba(255,255,255,.06)'}}><div className="text-lg font-bold" style={{fontFamily:F.r}}>{fl?due[ri].back:due[ri].front}</div></div>{!fl?<div className="text-[10px]" style={{color:'#475569'}}>Tap to flip</div>:<div className="grid grid-cols-4 gap-2"><Bt sm color="#EF4444" onClick={()=>review(1)}>AGAIN</Bt><Bt sm color="#F59E0B" onClick={()=>review(2)}>HARD</Bt><Bt sm color="#10B981" onClick={()=>review(3)}>GOOD</Bt><Bt sm color="#06B6D4" onClick={()=>review(5)}>EASY</Bt></div>}</div></Cd>}
<Md open={showA} onClose={()=>setShowA(false)} title="ADD CARD"><div className="space-y-3"><In value={sub} onChange={setSub} placeholder="Subject"/><In value={fr} onChange={setFr} placeholder="Front (Question)"/><textarea value={bk} onChange={e=>setBk(e.target.value)} placeholder="Back (Answer)" className="w-full px-3 py-2.5 rounded-lg text-sm text-white placeholder:text-gray-600 outline-none border h-24 resize-none" style={{background:'rgba(255,255,255,.03)',borderColor:'rgba(255,255,255,.06)',fontFamily:F.r}}/><Bt color="#06B6D4" cl="w-full" onClick={add}>ADD (+10 XP)</Bt></div></Md>
</div>;}

/* ═══ CODE ═══ */
function Code({addXP,cs,setCs,dl,setDL}:{addXP:(n:number,s?:Partial<Stats>)=>void;cs:CodingSes[];setCs:(s:CodingSes[])=>void;dl:DL;setDL:(d:DL)=>void}){
const[proj,setProj]=useState('');const[lang,setLang]=useState('JavaScript');
const timer=useTimer('sw');
const finish=()=>{const dur=Math.floor(timer.sec/60);if(dur<1)return;const xp=dur*4;const s:CodingSes={id:uid(),proj:proj||'Project',lang,dur,date:td(),xp};const ns=[s,...cs];setCs(ns);sv('cs',ns);addXP(xp,{INT:3,FOC:2,KNW:1});setDL({...dl,xp:dl.xp+xp,cMin:dl.cMin+dur});timer.reset();setProj('')};
const qLog=(d:number)=>{const xp=d*4;const s:CodingSes={id:uid(),proj:proj||'Coding',lang,dur:d,date:td(),xp};const ns=[s,...cs];setCs(ns);sv('cs',ns);addXP(xp,{INT:3,FOC:2});setDL({...dl,xp:dl.xp+xp,cMin:dl.cMin+d})};
return<div className="space-y-5"><ST color="#8B5CF6">💻 CODING</ST><Cd glow="#8B5CF6"><div className="text-center"><In value={proj} onChange={setProj} placeholder="Project" cl="mb-2"/><Sl value={lang} onChange={setLang} options={[{v:'JavaScript',l:'JavaScript'},{v:'TypeScript',l:'TypeScript'},{v:'Python',l:'Python'},{v:'React',l:'React'},{v:'Java',l:'Java'},{v:'C++',l:'C++'},{v:'Rust',l:'Rust'},{v:'Other',l:'Other'}]}/><div className="text-4xl font-black my-4" style={{fontFamily:F.m,color:'#8B5CF6',textShadow:'0 0 20px rgba(139,92,246,.3)'}}>{fmt(timer.sec)}</div><div className="flex justify-center gap-3"><Bt color="#8B5CF6" onClick={()=>timer.setRun(!timer.run)}>{timer.run?'⏸':'▶ START'}</Bt>{timer.sec>60&&<Bt color="#8B5CF6" v="outline" onClick={finish}>✓ FINISH</Bt>}<Bt color="#8B5CF6" v="ghost" onClick={timer.reset}>↺</Bt></div></div></Cd>
<div className="grid grid-cols-4 gap-2">{[15,30,60,120].map(d=><Cd key={d} glow="#8B5CF6" onClick={()=>qLog(d)}><div className="text-center"><div className="text-xs font-bold" style={{fontFamily:F.o,color:'#8B5CF6'}}>{d}m</div><div className="text-[8px]" style={{color:'#475569'}}>+{d*4}XP</div></div></Cd>)}</div>
<ST color="#8B5CF6">📋 LOG</ST>{cs.slice(0,8).map(s=><Cd key={s.id} cl="mb-2"><div className="flex justify-between"><div><div className="text-sm font-bold" style={{fontFamily:F.r}}>{s.proj}</div><div className="text-[10px]" style={{color:'#475569'}}>{s.lang}·{s.dur}m</div></div><div className="text-xs font-bold" style={{fontFamily:F.o,color:'#8B5CF6'}}>+{s.xp}XP</div></div></Cd>)}</div>;}

/* ═══ MATH ═══ */
function MathM(){
const[disp,setDisp]=useState('0');const[expr,setExpr]=useState('');const[view,setView]=useState<'calc'|'pct'|'form'>('calc');
const[pA,setPA]=useState('');const[pB,setPB]=useState('');
const[sipP,setSipP]=useState('5000');const[sipR,setSipR]=useState('12');const[sipT,setSipT]=useState('10');
const[emiP,setEmiP]=useState('500000');const[emiR,setEmiR]=useState('8');const[emiT,setEmiT]=useState('20');
const press=(v:string)=>{if(v==='C'){setDisp('0');setExpr('');return}if(v==='⌫'){setDisp(d=>d.length>1?d.slice(0,-1):'0');return}if(v==='±'){setDisp(d=>d.startsWith('-')?d.slice(1):'-'+d);return}if(v==='='){try{const e=(expr+disp).replace(/×/g,'*').replace(/÷/g,'/').replace(/π/g,String(Math.PI));const r=Function('"use strict";return ('+e+')')();setDisp(String(parseFloat(Number(r).toFixed(10))));setExpr('')}catch{setDisp('Error')}return}if(['+','-','×','÷'].includes(v)){setExpr(expr+disp+v);setDisp('0');return}if(v==='sin'){setDisp(String(parseFloat(Math.sin(parseFloat(disp)).toFixed(10))));return}if(v==='cos'){setDisp(String(parseFloat(Math.cos(parseFloat(disp)).toFixed(10))));return}if(v==='tan'){setDisp(String(parseFloat(Math.tan(parseFloat(disp)).toFixed(10))));return}if(v==='√'){setDisp(String(parseFloat(Math.sqrt(parseFloat(disp)).toFixed(10))));return}if(v==='x²'){setDisp(String(parseFloat((parseFloat(disp)**2).toFixed(10))));return}if(v==='log'){setDisp(String(parseFloat(Math.log10(parseFloat(disp)).toFixed(10))));return}if(v==='ln'){setDisp(String(parseFloat(Math.log(parseFloat(disp)).toFixed(10))));return}if(v==='π'){setDisp(String(Math.PI));return}setDisp(d=>d==='0'&&v!=='.'?v:d+v)};
const sipFV=useMemo(()=>{const p=parseFloat(sipP)||0,r=(parseFloat(sipR)||0)/100/12,t=(parseFloat(sipT)||0)*12;return r>0?p*((Math.pow(1+r,t)-1)/r)*(1+r):p*t},[sipP,sipR,sipT]);
const emiAmt=useMemo(()=>{const p=parseFloat(emiP)||0,r=(parseFloat(emiR)||0)/100/12,t=(parseFloat(emiT)||0)*12;return r>0?p*r*Math.pow(1+r,t)/(Math.pow(1+r,t)-1):p/t},[emiP,emiR,emiT]);
return<div className="space-y-5"><ST color="#F59E0B">🔢 MATHEMATICS</ST>
<div className="flex gap-2 flex-wrap">{(['calc','pct','form'] as const).map(v=><Bt key={v} sm color="#F59E0B" v={view===v?'solid':'outline'} onClick={()=>setView(v)}>{v==='calc'?'CALC':v==='pct'?'%/SIP/EMI':'FORMULAS'}</Bt>)}</div>
{view==='calc'&&<Cd glow="#F59E0B"><div className="text-right mb-3"><div className="text-[10px] h-4 truncate" style={{color:'#475569',fontFamily:F.m}}>{expr}</div><div className="text-3xl font-black truncate" style={{fontFamily:F.m,color:'#F59E0B'}}>{disp}</div></div><div className="grid grid-cols-5 gap-1.5">{['sin','cos','tan','log','ln','7','8','9','÷','√','4','5','6','×','x²','1','2','3','-','π','0','.','±','+','⌫','C','','','','='].map((b,i)=>b?<button key={i} onClick={()=>press(b)} className="py-2.5 rounded-lg text-xs font-bold active:scale-90" style={{fontFamily:['=','C','⌫'].includes(b)?F.o:F.m,background:b==='='?`linear-gradient(135deg,${C.c},${C.p})`:['C','⌫'].includes(b)?'rgba(239,68,68,.12)':'rgba(255,255,255,.04)',color:b==='='?'#fff':['C','⌫'].includes(b)?'#EF4444':['+','-','×','÷'].includes(b)?'#F59E0B':'#e2e8f0',border:`1px solid ${b==='='?'transparent':'rgba(255,255,255,.06)'}`}}>{b}</button>:<div key={i}/>)}</div></Cd>}
{view==='pct'&&<><Cd glow="#F59E0B"><div className="text-[10px] tracking-[2px] font-bold mb-2" style={{fontFamily:F.o,color:'#F59E0B'}}>PERCENTAGE</div><div className="flex gap-2 items-center"><In type="number" value={pA} onChange={setPA} placeholder="X"/><span style={{color:'#F59E0B'}}>% of</span><In type="number" value={pB} onChange={setPB} placeholder="Y"/></div>{pA&&pB&&<div className="text-xl font-black text-center mt-2" style={{fontFamily:F.o,color:C.c}}>= {((parseFloat(pA)/100)*parseFloat(pB)).toFixed(2)}</div>}</Cd>
<Cd glow="#10B981"><div className="text-[10px] tracking-[2px] font-bold mb-2" style={{fontFamily:F.o,color:'#10B981'}}>SIP CALCULATOR</div><div className="space-y-2"><In type="number" value={sipP} onChange={setSipP} placeholder="Monthly (₹)"/><In type="number" value={sipR} onChange={setSipR} placeholder="Rate (%/yr)"/><In type="number" value={sipT} onChange={setSipT} placeholder="Years"/></div><div className="text-center mt-3"><div className="text-xl font-black" style={{fontFamily:F.o,color:'#10B981'}}>₹{Math.round(sipFV).toLocaleString()}</div><div className="text-xs" style={{color:'#94A3B8'}}>Invested: ₹{(parseFloat(sipP)||0)*parseInt(sipT)*12}</div></div></Cd>
<Cd glow="#EF4444"><div className="text-[10px] tracking-[2px] font-bold mb-2" style={{fontFamily:F.o,color:'#EF4444'}}>EMI CALCULATOR</div><div className="space-y-2"><In type="number" value={emiP} onChange={setEmiP} placeholder="Loan (₹)"/><In type="number" value={emiR} onChange={setEmiR} placeholder="Rate (%/yr)"/><In type="number" value={emiT} onChange={setEmiT} placeholder="Years"/></div><div className="text-center mt-3"><div className="text-xl font-black" style={{fontFamily:F.o,color:'#EF4444'}}>₹{Math.round(emiAmt).toLocaleString()}/mo</div><div className="text-xs" style={{color:'#94A3B8'}}>Total: ₹{Math.round(emiAmt*parseInt(emiT)*12).toLocaleString()}</div></div></Cd></>}
{view==='form'&&[{cat:'Geometry',items:['Area Circle: πr²','Circumference: 2πr','Area Triangle: ½bh','Volume Sphere: 4/3πr³','Pythagorean: a²+b²=c²']},{cat:'Algebra',items:['Quadratic: (-b±√(b²-4ac))/2a','Slope: (y₂-y₁)/(x₂-x₁)']},{cat:'Calculus',items:['d/dx(xⁿ)=nxⁿ⁻¹','∫xⁿdx=xⁿ⁺¹/(n+1)+C']},{cat:'Physics',items:['F=ma','E=mc²','v=u+at','KE=½mv²']},{cat:'Finance',items:['CI: A=P(1+r/n)^(nt)','SI: I=Prt','ROI: (Gain-Cost)/Cost×100']}].map(f=><Cd key={f.cat} glow="#F59E0B" cl="mb-2"><div className="text-xs font-bold mb-2" style={{fontFamily:F.o,color:'#F59E0B'}}>{f.cat.toUpperCase()}</div>{f.items.map((it,i)=><div key={i} className="text-sm py-1 border-t first:border-0" style={{fontFamily:F.m,color:'#94A3B8',borderColor:'rgba(255,255,255,.04)',fontSize:'12px'}}>{it}</div>)}</Cd>)}
</div>;}

/* ═══ FINANCE ═══ */
function Finance({txs,setTxs,goals,setGoals}:{txs:Tx[];setTxs:(t:Tx[])=>void;goals:Goal[];setGoals:(g:Goal[])=>void}){
const[showA,setShowA]=useState(false);const[showG,setShowG]=useState(false);const[tType,setTType]=useState<'in'|'out'>('out');const[tCat,setTCat]=useState('Food');const[tAmt,setTAmt]=useState('');const[tDesc,setTDesc]=useState('');const[gN,setGN]=useState('');const[gT,setGT]=useState('');
const mtx=txs.filter(t=>t.date.slice(0,7)===td().slice(0,7));const inc=mtx.filter(t=>t.type==='in').reduce((a,b)=>a+b.amt,0);const exp=mtx.filter(t=>t.type==='out').reduce((a,b)=>a+b.amt,0);
const addTx=()=>{if(!tAmt)return;const t:Tx={id:uid(),type:tType,cat:tCat,amt:parseFloat(tAmt),desc:tDesc,date:td()};const nt=[t,...txs];setTxs(nt);sv('txs',nt);setShowA(false);setTAmt('');setTDesc('')};
const addG=()=>{if(!gN||!gT)return;const g:Goal={id:uid(),name:gN,tgt:parseFloat(gT),cur:0,cat:'savings'};const ng=[...goals,g];setGoals(ng);sv('goals',ng);setShowG(false);setGN('');setGT('')};
return<div className="space-y-5"><ST color="#F59E0B">💰 FINANCE</ST>
<div className="grid grid-cols-3 gap-2"><Cd glow="#10B981"><SN icon="📈" value={`$${inc}`} label="INCOME" color="#10B981"/></Cd><Cd glow="#EF4444"><SN icon="📉" value={`$${exp}`} label="EXPENSES" color="#EF4444"/></Cd><Cd glow={inc-exp>=0?C.c:'#EF4444'}><SN icon="💎" value={`$${inc-exp}`} label="BALANCE" color={inc-exp>=0?C.c:'#EF4444'}/></Cd></div>
<Bt color="#F59E0B" cl="w-full" onClick={()=>setShowA(true)}>+ TRANSACTION</Bt>
<ST color="#10B981">🎯 GOALS</ST>{goals.map(g=><Cd key={g.id} glow="#10B981" cl="mb-2"><div className="flex justify-between mb-1"><span className="text-sm font-bold" style={{fontFamily:F.r}}>{g.name}</span><span className="text-xs font-bold" style={{fontFamily:F.o,color:'#10B981'}}>${g.cur}/${g.tgt}</span></div><PB val={g.cur} max={g.tgt} color="#10B981"/><div className="flex gap-2 mt-2">{[10,50,100].map(a=><Bt key={a} sm v="ghost" color="#10B981" onClick={()=>{const ng=goals.map(sg=>sg.id===g.id?{...sg,cur:Math.min(sg.cur+a,sg.tgt)}:sg);setGoals(ng);sv('goals',ng)}}>+${a}</Bt>)}</div></Cd>)}<Bt color="#10B981" v="outline" cl="w-full" onClick={()=>setShowG(true)}>+ NEW GOAL</Bt>
<ST color="#F59E0B">📋 TRANSACTIONS</ST>{txs.slice(0,8).map(t=><Cd key={t.id} cl="mb-2"><div className="flex justify-between"><div><div className="text-sm font-bold" style={{fontFamily:F.r}}>{t.desc||t.cat}</div><div className="text-[10px]" style={{color:'#475569'}}>{t.cat}·{t.date}</div></div><div className="text-sm font-bold" style={{fontFamily:F.o,color:t.type==='in'?'#10B981':'#EF4444'}}>{t.type==='in'?'+':'-'}${t.amt}</div></div></Cd>)}
<Md open={showA} onClose={()=>setShowA(false)} title="ADD TRANSACTION"><div className="space-y-3"><div className="flex gap-2"><Bt sm color="#10B981" v={tType==='in'?'solid':'outline'} onClick={()=>setTType('in')}>INCOME</Bt><Bt sm color="#EF4444" v={tType==='out'?'solid':'outline'} onClick={()=>setTType('out')}>EXPENSE</Bt></div><Sl value={tCat} onChange={setTCat} options={tType==='out'?[{v:'Food',l:'Food'},{v:'Transport',l:'Transport'},{v:'Bills',l:'Bills'},{v:'Shopping',l:'Shopping'},{v:'Other',l:'Other'}]:[{v:'Salary',l:'Salary'},{v:'Freelance',l:'Freelance'},{v:'Other',l:'Other'}]}/><In type="number" value={tAmt} onChange={setTAmt} placeholder="Amount"/><In value={tDesc} onChange={setTDesc} placeholder="Description"/><Bt color="#F59E0B" cl="w-full" onClick={addTx}>SAVE</Bt></div></Md>
<Md open={showG} onClose={()=>setShowG(false)} title="NEW GOAL"><div className="space-y-3"><In value={gN} onChange={setGN} placeholder="Goal name"/><In type="number" value={gT} onChange={setGT} placeholder="Target ($)"/><Bt color="#10B981" cl="w-full" onClick={addG}>CREATE</Bt></div></Md>
</div>;}

/* ═══ PRODUCTIVITY ═══ */
function Prod({addXP,habits,setHabits,tasks,setTasks,dl,setDL}:{addXP:(n:number,s?:Partial<Stats>)=>void;habits:Habit[];setHabits:(h:Habit[])=>void;tasks:Task[];setTasks:(t:Task[])=>void;dl:DL;setDL:(d:DL)=>void}){
const[showH,setShowH]=useState(false);const[showT,setShowT]=useState(false);const[hN,setHN]=useState('');const[hI,setHI]=useState('💪');const[tT,setTT]=useState('');const[tP,setTP]=useState<Task['pri']>('med');
const toggleH=(id:string)=>{const t=td();const nh=habits.map(h=>{if(h.id!==id)return h;const done=h.dates.includes(t);if(done)return{...h,dates:h.dates.filter(d=>d!==t)};addXP(h.xpPer,{DIS:1,CON:2});setDL({...dl,xp:dl.xp+h.xpPer,habits:dl.habits+1});return{...h,dates:[...h.dates,t],streak:h.streak+1}});setHabits(nh);sv('habits',nh)};
const toggleT=(id:string)=>{const nt=tasks.map(t=>{if(t.id!==id)return t;if(!t.done){addXP(30,{DIS:1,FOC:1});setDL({...dl,xp:dl.xp+30,tasks:dl.tasks+1})}return{...t,done:!t.done}});setTasks(nt);sv('tasks',nt)};
const priC:Record<string,string>={low:'#10B981',med:'#3B82F6',high:'#F59E0B',urgent:'#EF4444'};
return<div className="space-y-5"><ST color="#EC4899">🎯 PRODUCTIVITY</ST>
<ST color="#F97316">🔗 HABITS</ST>{habits.map(h=>{const done=h.dates.includes(td());return<Cd key={h.id} glow={done?'#10B981':''} cl="mb-2" onClick={()=>toggleH(h.id)}><div className="flex items-center gap-3"><div className={`text-lg ${done?'':'opacity-40'}`}>{h.icon}</div><div className="flex-1"><div className={`text-sm font-bold ${done?'line-through opacity-50':''}`} style={{fontFamily:F.r}}>{h.name}</div><div className="text-[9px]" style={{color:'#475569'}}>🔥{h.streak}·+{h.xpPer}XP</div></div><div className={`w-6 h-6 rounded-full border-2 flex items-center justify-center text-xs ${done?'border-green-400 bg-green-400/20 text-green-400':'border-gray-600'}`}>{done&&'✓'}</div></div></Cd>})}
<Bt color="#F97316" v="outline" cl="w-full" onClick={()=>setShowH(true)}>+ HABIT</Bt>
<ST color="#3B82F6">📋 TASKS</ST>{tasks.filter(t=>!t.done).map(t=><Cd key={t.id} cl="mb-2"><div className="flex items-center gap-3"><button onClick={()=>toggleT(t.id)} className="w-6 h-6 rounded-full border-2 flex-shrink-0" style={{borderColor:priC[t.pri]}}/><div className="flex-1 min-w-0"><div className="text-sm font-bold truncate" style={{fontFamily:F.r}}>{t.title}</div><div className="text-[9px]" style={{color:priC[t.pri]}}>{t.pri.toUpperCase()}</div></div><button onClick={()=>{setTasks(tasks.filter(x=>x.id!==t.id));sv('tasks',tasks.filter(x=>x.id!==t.id))}} className="text-gray-600 text-xs">✕</button></div></Cd>)}
<Bt color="#3B82F6" cl="w-full" onClick={()=>setShowT(true)}>+ TASK</Bt>
<Md open={showH} onClose={()=>setShowH(false)} title="NEW HABIT"><div className="space-y-3"><In value={hN} onChange={setHN} placeholder="Habit name"/><div className="flex gap-2 flex-wrap">{['💪','📚','💻','🧘','🏃','💧','📝','🎯','🔥','💤'].map(e=><button key={e} onClick={()=>setHI(e)} className={`w-10 h-10 rounded-lg text-lg flex items-center justify-center border ${hI===e?'border-cyan-400':'border-transparent'}`} style={{background:'rgba(255,255,255,.04)'}}>{e}</button>)}</div><Bt color="#F97316" cl="w-full" onClick={()=>{if(!hN)return;const h:Habit={id:uid(),name:hN,icon:hI,dates:[],streak:0,xpPer:20};setHabits([...habits,h]);sv('habits',[...habits,h]);setShowH(false);setHN('')}}>CREATE</Bt></div></Md>
<Md open={showT} onClose={()=>setShowT(false)} title="NEW TASK"><div className="space-y-3"><In value={tT} onChange={setTT} placeholder="Task title"/><div className="flex gap-2">{(['low','med','high','urgent'] as const).map(p=><Bt key={p} sm color={priC[p]} v={tP===p?'solid':'outline'} onClick={()=>setTP(p)}>{p.toUpperCase()}</Bt>)}</div><Bt color="#3B82F6" cl="w-full" onClick={()=>{if(!tT)return;const t:Task={id:uid(),title:tT,pri:tP,done:false,due:td(),mod:'general'};setTasks([t,...tasks]);sv('tasks',[t,...tasks]);setShowT(false);setTT('')}}>ADD</Bt></div></Md>
</div>;}

/* ═══ KNOWLEDGE ═══ */
function Know(){
const[selCat,setSelCat]=useState<string|null>(null);const[selArt,setSelArt]=useState<typeof articles[0]|null>(null);
const cc:Record<string,string>={Fitness:'#EF4444',Nutrition:'#F97316','Exercise Science':'#EC4899','Weight Loss':'#F59E0B','Muscle Building':'#EF4444','Health Basics':'#10B981','Study Techniques':'#10B981','Learning Methods':'#3B82F6',Mathematics:'#F59E0B',Physics:'#8B5CF6',Chemistry:'#06B6D4',Biology:'#10B981','Computer Science':'#3B82F6',Finance:'#F59E0B',Economics:'#F97316',Productivity:'#EC4899','Time Management':'#F59E0B','Self Improvement':'#06B6D4'};
const ci:Record<string,string>={Fitness:'💪',Nutrition:'🥗','Exercise Science':'🔬','Weight Loss':'📉','Muscle Building':'💪','Health Basics':'❤️','Study Techniques':'🧠','Learning Methods':'📊',Mathematics:'🔢',Physics:'⚛️',Chemistry:'🧪',Biology:'🧬','Computer Science':'💻',Finance:'💰',Economics:'📈',Productivity:'🎯','Time Management':'⏰','Self Improvement':'⚡'};
return<div className="space-y-5"><ST color="#06B6D4">📖 KNOWLEDGE HUB</ST>
{!selArt?<><div className="grid grid-cols-3 gap-2">{KC.map(cat=><Cd key={cat} glow={cc[cat]||C.c} onClick={()=>setSelCat(selCat===cat?null:cat)}><div className="text-center"><div className="text-xl mb-0.5">{ci[cat]||'📖'}</div><div className="text-[8px] font-bold tracking-[1px]" style={{fontFamily:F.r,color:cc[cat]||C.c}}>{cat.toUpperCase()}</div></div></Cd>)}</div>{selCat&&<div className="space-y-2 mt-3">{articles.filter(a=>a.cat===selCat).map(a=><Cd key={a.id} glow={cc[a.cat]} onClick={()=>setSelArt(a)}><div className="flex items-center gap-3"><div className="text-xl">{a.icon}</div><div><div className="text-sm font-bold" style={{fontFamily:F.r}}>{a.title}</div><div className="text-[10px] lc2" style={{color:'#475569'}}>{a.content.slice(0,50)}...</div></div></div></Cd>)}</div>}</>
:<div><Bt sm v="ghost" color={C.c} onClick={()=>setSelArt(null)} cl="mb-3">← BACK</Bt><Cd glow={cc[selArt.cat]}><div className="text-3xl mb-3">{selArt.icon}</div><div className="text-[10px] tracking-wider mb-1" style={{fontFamily:F.o,color:cc[selArt.cat]}}>{selArt.cat.toUpperCase()}</div><h2 className="text-lg font-bold mb-4" style={{fontFamily:F.r}}>{selArt.title}</h2><div className="text-sm leading-relaxed" style={{color:'#94A3B8'}}>{selArt.content}</div></Cd></div>}
<div className="text-[8px] text-center p-2 rounded-lg mt-3" style={{background:'rgba(255,255,255,.01)',color:'#334155',fontFamily:F.r}}>⚠️ Educational content. Consult professionals for important decisions.</div>
</div>;}

/* ═══ ANALYTICS ═══ */
function Analytics({prof,stats,dls,workouts,ses,cs,txs,qr}:{prof:Prof;stats:Stats;dls:DL[];workouts:Workout[];ses:StudySes[];cs:CodingSes[];txs:Tx[];qr:QR[]}){
const recent=dls.slice(-7);const totalXP=recent.reduce((a,b)=>a+b.xp,0);const maxXP=Math.max(...recent.map(d=>d.xp),1);
return<div className="space-y-5"><ST color={C.c}>📊 ANALYTICS</ST>
<div className="grid grid-cols-2 gap-2"><Cd glow={C.c}><SN icon="⚡" value={totalXP} label="WEEK XP" color={C.c}/></Cd><Cd glow={C.p}><SN icon="💎" value={prof.pwr} label="POWER" color={C.p}/></Cd><Cd glow="#EF4444"><SN icon="💪" value={`${recent.reduce((a,b)=>a+b.wMin,0)}m`} label="TRAINING" color="#EF4444"/></Cd><Cd glow="#10B981"><SN icon="📚" value={`${recent.reduce((a,b)=>a+b.sMin,0)}m`} label="STUDY" color="#10B981"/></Cd><Cd glow="#8B5CF6"><SN icon="💻" value={`${recent.reduce((a,b)=>a+b.cMin,0)}m`} label="CODE" color="#8B5CF6"/></Cd><Cd glow="#F59E0B"><SN icon="🔥" value={prof.streak} label="STREAK" color="#F59E0B"/></Cd></div>
<Cd glow={C.c}><div className="text-[10px] tracking-[2px] mb-3 font-bold" style={{fontFamily:F.o,color:C.c}}>XP TREND</div><div className="flex items-end justify-between h-24 gap-1">{recent.map((d,i)=>{const h=(d.xp/maxXP)*100;const isT=d.date===td();return<div key={i} className="flex-1 flex flex-col items-center"><div className="w-full flex-1 flex items-end"><div className="w-full rounded-t-sm" style={{height:`${Math.max(h,4)}%`,background:isT?`linear-gradient(180deg,${C.c},${C.p})`:`linear-gradient(180deg,${C.p}50,${C.p}15)`,boxShadow:isT?`0 0 10px ${C.c}40`:'none'}}/></div><span className="text-[7px] mt-1 font-bold" style={{fontFamily:F.o,color:isT?C.c:'#334155'}}>{d.date.slice(8)}</span></div>})}</div></Cd>
<Cd glow={C.p}><div className="text-[10px] tracking-[2px] mb-3 font-bold" style={{fontFamily:F.o,color:C.p}}>ATTRIBUTES</div><div className="grid grid-cols-4 gap-2">{(Object.entries(stats) as[string,number][]).map(([k,v])=>{const cs2:Record<string,string>={STR:'#EF4444',AGI:'#3B82F6',END:'#10B981',INT:'#8B5CF6',DIS:'#F59E0B',FOC:'#EC4899',KNW:'#06B6D4',CON:'#F97316'};return<div key={k} className="text-center"><div className="text-xs font-black mb-1" style={{fontFamily:F.o,color:cs2[k]}}>{v}</div><PB val={Math.min(v,100)} max={100} color={cs2[k]} h="h-1"/><div className="text-[7px] font-bold" style={{fontFamily:F.o,color:`${cs2[k]}80`}}>{k}</div></div>})}</div></Cd>
<Cd glow="#F59E0B"><div className="text-[10px] tracking-[2px] mb-3 font-bold" style={{fontFamily:F.o,color:'#F59E0B'}}>ACTIVITY</div>{[{l:'Workouts',v:workouts.length,c:'#EF4444'},{l:'Study',v:ses.length,c:'#10B981'},{l:'Coding',v:cs.length,c:'#8B5CF6'},{l:'Exams',v:qr.length,c:'#EC4899'},{l:'Finance',v:txs.length,c:'#F59E0B'}].map(m=><div key={m.l} className="flex justify-between py-2 border-t first:border-0 text-xs" style={{borderColor:'rgba(255,255,255,.04)'}}><span style={{color:m.c}}>{m.l}</span><span style={{fontFamily:F.o,color:'#94A3B8'}}>{m.v}</span></div>)}</Cd>
</div>;}

/* ═══ SETTINGS ═══ */
function Cfg({prof,setProf,resetAll}:{prof:Prof;setProf:(p:Prof)=>void;resetAll:()=>void}){
const[name,setName]=useState(prof.name);const[showR,setShowR]=useState(false);
const exportData=()=>{const data:Record<string,unknown>={};const keys=['prof','stats','workouts','study_ses','cs','txs','goals','habits','tasks','notes','fcs','qr','day_logs','achs'];keys.forEach(k=>{try{const v=localStorage.getItem('sf_'+k);if(v)data[k]=JSON.parse(v)}catch{}});const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`shadowfit_backup_${td()}.json`;a.click();URL.revokeObjectURL(url)};
return<div className="space-y-5"><ST color="#94A3B8">⚙️ SETTINGS</ST>
<Cd glow={C.c}><div className="space-y-3"><div className="text-[10px] tracking-[2px] font-bold" style={{fontFamily:F.o,color:C.c}}>PROFILE</div><In value={name} onChange={setName} placeholder="Hunter Name"/><Bt color={C.c} cl="w-full" onClick={()=>{const np={...prof,name};setProf(np);sv('prof',np)}}>SAVE</Bt></div></Cd>
<Cd glow={C.p}><div className="text-[10px] tracking-[2px] font-bold mb-3" style={{fontFamily:F.o,color:C.p}}>SYSTEM</div><div className="space-y-2 text-xs" style={{fontFamily:F.r,color:'#94A3B8'}}>{[['Version','3.0.0',C.c],['Rank',`${prof.rank}-Rank`,RC[prof.rank]],['Level',String(prof.level),C.c],['Total XP',prof.totalXp.toLocaleString(),'#F59E0B'],['Class',`Class ${prof.cls}`,'#8B5CF6'],['Board',prof.board,'#10B981'],['Streak',`${prof.streak} days`,'#EF4444']].map(([l,v,c])=><div key={l} className="flex justify-between"><span>{l}</span><span style={{color:c}}>{v}</span></div>)}</div></Cd>
<Cd glow="#10B981"><div className="text-[10px] tracking-[2px] font-bold mb-3" style={{fontFamily:F.o,color:'#10B981'}}>DATA</div><Bt color="#10B981" v="outline" cl="w-full mb-2" onClick={exportData}>📥 EXPORT BACKUP</Bt></Cd>
<Cd glow="#EF4444"><Bt color="#EF4444" v="outline" cl="w-full" onClick={()=>setShowR(true)}>RESET ALL DATA</Bt></Cd>
<Md open={showR} onClose={()=>setShowR(false)} title="CONFIRM RESET"><div className="text-center py-4"><div className="text-3xl mb-3">⚠️</div><p className="text-sm mb-4" style={{color:'#94A3B8'}}>Delete ALL data?</p><div className="flex gap-3"><Bt color="#94A3B8" v="outline" cl="flex-1" onClick={()=>setShowR(false)}>CANCEL</Bt><Bt color="#EF4444" cl="flex-1" onClick={()=>{resetAll();setShowR(false)}}>DELETE</Bt></div></div></Md>
</div>;}

/* ═══ COLLEGE / UNIVERSITY ═══ */
function College({addXP,edu,setEdu,semesters,setSemesters,dl,setDL}:{addXP:(n:number,s?:Partial<Stats>)=>void;edu:EduProfile;setEdu:(e:EduProfile)=>void;semesters:Semester[];setSemesters:(s:Semester[])=>void;dl:DL;setDL:(d:DL)=>void}){
const[view,setView]=useState<'home'|'sem'|'sub'|'add'|'addSub'|'assign'|'proj'>('home');
const[selSem,setSelSem]=useState('');const[selSub,setSelSub]=useState('');
const[sName,setSName]=useState('');const[subName,setSubName]=useState('');const[subCred,setSubCred]=useState('3');
const[aTitle,setATitle]=useState('');const[pTitle,setPTitle]=useState('');const[pDesc,setPDesc]=useState('');
const semObj=semesters.find(s=>s.id===selSem);
const subObj=semObj?.subjects.find(s=>s.id===selSub);
const cgpa=semesters.length>0?parseFloat((semesters.reduce((a,b)=>a+b.gpa,0)/semesters.length).toFixed(2)):0;
const totalAtt=semObj?semObj.subjects.length>0?Math.round(semObj.subjects.reduce((a,b)=>a+b.attendance,0)/semObj.subjects.length):0:0;
const addSem=()=>{if(!sName)return;const s:Semester={id:uid(),name:sName,year:edu.year,sem:edu.semester,subjects:[],gpa:0};const ns=[...semesters,s];setSemesters(ns);sv('semesters',ns);setView('home');setSName('');addXP(20,{DIS:1})};
const addSubject=()=>{if(!subName||!selSem)return;const sub:SemSubject={id:uid(),name:subName,credits:parseInt(subCred)||3,grade:'',attendance:0,intMarks:0,intMax:40,practMarks:0,practMax:30,assignments:[],projects:[]};const ns=semesters.map(s=>s.id===selSem?{...s,subjects:[...s.subjects,sub]}:s);setSemesters(ns);sv('semesters',ns);setView('sem');setSubName('')};
const setGrade=(subId:string,grade:string)=>{const ns=semesters.map(s=>{if(s.id!==selSem)return s;const subs=s.subjects.map(sub=>sub.id===subId?{...sub,grade}:sub);return{...s,subjects:subs,gpa:calcGPA(subs)}});setSemesters(ns);sv('semesters',ns)};
const setAtt=(subId:string,att:number)=>{const ns=semesters.map(s=>s.id===selSem?{...s,subjects:s.subjects.map(sub=>sub.id===subId?{...sub,attendance:Math.min(100,Math.max(0,att))}:sub)}:s);setSemesters(ns);sv('semesters',ns)};
const addAssign=()=>{if(!aTitle||!selSub)return;const a={id:uid(),title:aTitle,done:false,due:td(),score:0,max:100};const ns=semesters.map(s=>s.id===selSem?{...s,subjects:s.subjects.map(sub=>sub.id===selSub?{...sub,assignments:[...sub.assignments,a]}:sub)}:s);setSemesters(ns);sv('semesters',ns);setATitle('');setView('sub')};
const toggleAssign=(aId:string)=>{const ns=semesters.map(s=>s.id===selSem?{...s,subjects:s.subjects.map(sub=>sub.id===selSub?{...sub,assignments:sub.assignments.map(a=>a.id===aId?{...a,done:!a.done}:a)}:sub)}:s);setSemesters(ns);sv('semesters',ns);addXP(25,{DIS:1,KNW:1});setDL({...dl,xp:dl.xp+25,tasks:dl.tasks+1})};
const addProject=()=>{if(!pTitle)return;const p={id:uid(),title:pTitle,status:'pending' as const,desc:pDesc};const ns=semesters.map(s=>s.id===selSem?{...s,subjects:s.subjects.map(sub=>sub.id===selSub?{...sub,projects:[...sub.projects,p]}:sub)}:s);setSemesters(ns);sv('semesters',ns);setPTitle('');setPDesc('');setView('sub')};
const updateProjStatus=(pId:string,status:'pending'|'progress'|'done')=>{const ns=semesters.map(s=>s.id===selSem?{...s,subjects:s.subjects.map(sub=>sub.id===selSub?{...sub,projects:sub.projects.map(p=>p.id===pId?{...p,status}:p)}:sub)}:s);setSemesters(ns);sv('semesters',ns);if(status==='done'){addXP(50,{INT:2,DIS:1});setDL({...dl,xp:dl.xp+50,tasks:dl.tasks+1})}};
const gradeOpts=[{v:'',l:'—'},{v:'O',l:'O (10)'},{v:'A+',l:'A+ (9)'},{v:'A',l:'A (8)'},{v:'B+',l:'B+ (7)'},{v:'B',l:'B (6)'},{v:'C',l:'C (5)'},{v:'D',l:'D (4)'},{v:'F',l:'F (0)'}];
const eduLevels=[{v:'school',l:'School (1-12)'},{v:'diploma',l:'Diploma'},{v:'college',l:'College/UG'},{v:'university',l:'University/PG'},{v:'competitive',l:'Competitive Exams'},{v:'professional',l:'Professional'},{v:'self',l:'Self Learner'}];
const pStatC:Record<string,string>={pending:'#F59E0B',progress:'#3B82F6',done:'#10B981'};
return<div className="space-y-5">
{view==='home'&&<><ST color="#8B5CF6">🏛️ COLLEGE & UNIVERSITY</ST>
<Cd glow="#8B5CF6"><div className="text-[10px] tracking-[2px] font-bold mb-3" style={{fontFamily:F.o,color:'#8B5CF6'}}>EDUCATION PROFILE</div><div className="space-y-2">
<Sl value={edu.level} onChange={v=>{const ne={...edu,level:v as any};setEdu(ne);sv('edu',ne)}} options={eduLevels}/>
<Sl value={edu.country} onChange={v=>{const ne={...edu,country:v};setEdu(ne);sv('edu',ne)}} options={countries.map(c=>({v:c,l:c}))}/>
<Sl value={edu.board} onChange={v=>{const ne={...edu,board:v};setEdu(ne);sv('edu',ne)}} options={eduBoards.map(b=>({v:b,l:b}))}/>
<div className="grid grid-cols-2 gap-2"><In value={edu.institution} onChange={v=>{const ne={...edu,institution:v};setEdu(ne);sv('edu',ne)}} placeholder="Institution"/><Sl value={edu.program} onChange={v=>{const ne={...edu,program:v};setEdu(ne);sv('edu',ne)}} options={[{v:'',l:'Select Program'},...collegePrograms.map(p=>({v:p.name,l:`${p.icon} ${p.name}`}))]}/></div>
</div></Cd>
<div className="grid grid-cols-2 gap-2"><Cd glow="#8B5CF6"><SN icon="🎓" value={cgpa||'—'} label="CGPA" color="#8B5CF6"/></Cd><Cd glow="#10B981"><SN icon="📊" value={semesters.length} label="SEMESTERS" color="#10B981"/></Cd></div>
<ST color="#8B5CF6">📚 SEMESTERS</ST>{semesters.map(s=><Cd key={s.id} glow="#8B5CF6" cl="mb-2" onClick={()=>{setSelSem(s.id);setView('sem')}}><div className="flex justify-between"><div><div className="text-sm font-bold" style={{fontFamily:F.r}}>{s.name}</div><div className="text-[9px]" style={{color:'#475569'}}>{s.subjects.length} subjects</div></div><div className="text-right"><div className="text-sm font-black" style={{fontFamily:F.o,color:s.gpa>=8?'#10B981':s.gpa>=6?'#F59E0B':s.gpa>0?'#EF4444':'#475569'}}>{s.gpa||'—'}</div><div className="text-[8px]" style={{color:'#475569'}}>GPA</div></div></div></Cd>)}<Bt color="#8B5CF6" cl="w-full" onClick={()=>setView('add')}>+ ADD SEMESTER</Bt></>}
{view==='add'&&<><Bt sm v="ghost" color={C.c} onClick={()=>setView('home')} cl="mb-2">← BACK</Bt><Cd glow="#8B5CF6"><div className="space-y-3"><div className="text-[10px] tracking-[2px] font-bold" style={{fontFamily:F.o,color:'#8B5CF6'}}>NEW SEMESTER</div><In value={sName} onChange={setSName} placeholder="e.g. Semester 3 - Fall 2025"/><Bt color="#8B5CF6" cl="w-full" onClick={addSem}>CREATE (+20 XP)</Bt></div></Cd></>}
{view==='sem'&&semObj&&<><Bt sm v="ghost" color={C.c} onClick={()=>setView('home')} cl="mb-2">← BACK</Bt><ST color="#8B5CF6">📚 {semObj.name.toUpperCase()}</ST>
<div className="grid grid-cols-3 gap-2"><Cd glow="#8B5CF6"><SN value={semObj.gpa||'—'} label="GPA" color="#8B5CF6"/></Cd><Cd glow="#10B981"><SN value={semObj.subjects.length} label="SUBJECTS" color="#10B981"/></Cd><Cd glow="#F59E0B"><SN value={`${totalAtt}%`} label="ATTENDANCE" color={totalAtt>=75?'#10B981':'#EF4444'}/></Cd></div>
{semObj.subjects.map(sub=><Cd key={sub.id} glow="#8B5CF6" cl="mb-2" onClick={()=>{setSelSub(sub.id);setView('sub')}}><div className="flex items-center justify-between"><div><div className="text-sm font-bold" style={{fontFamily:F.r}}>{sub.name}</div><div className="text-[9px]" style={{color:'#475569'}}>{sub.credits} credits · {sub.assignments.filter(a=>a.done).length}/{sub.assignments.length} done · {sub.projects.filter(p=>p.status==='done').length}/{sub.projects.length} proj</div></div><div className="text-right"><Sl value={sub.grade} onChange={v=>setGrade(sub.id,v)} options={gradeOpts}/></div></div><div className="flex items-center gap-2 mt-2"><span className="text-[9px]" style={{color:'#475569'}}>Att:</span><input type="range" min="0" max="100" value={sub.attendance} onChange={e=>setAtt(sub.id,parseInt(e.target.value))} className="flex-1 h-1 accent-cyan-400" style={{accentColor:sub.attendance>=75?'#10B981':'#EF4444'}}/><span className="text-[9px] font-bold" style={{color:sub.attendance>=75?'#10B981':'#EF4444'}}>{sub.attendance}%</span></div></Cd>)}<Bt color="#8B5CF6" v="outline" cl="w-full" onClick={()=>setView('addSub')}>+ ADD SUBJECT</Bt></>}
{view==='addSub'&&<><Bt sm v="ghost" color={C.c} onClick={()=>setView('sem')} cl="mb-2">← BACK</Bt><Cd glow="#8B5CF6"><div className="space-y-3"><In value={subName} onChange={setSubName} placeholder="Subject name"/><In type="number" value={subCred} onChange={setSubCred} placeholder="Credits"/><Bt color="#8B5CF6" cl="w-full" onClick={addSubject}>ADD SUBJECT</Bt></div></Cd></>}
{view==='sub'&&semObj&&subObj&&<><Bt sm v="ghost" color={C.c} onClick={()=>setView('sem')} cl="mb-2">← BACK</Bt><ST color="#8B5CF6">{subObj.name.toUpperCase()}</ST>
<div className="grid grid-cols-3 gap-2"><Cd glow="#8B5CF6"><SN value={subObj.grade||'—'} label="GRADE" color="#8B5CF6"/></Cd><Cd glow="#10B981"><SN value={`${subObj.attendance}%`} label="ATTENDANCE" color={subObj.attendance>=75?'#10B981':'#EF4444'}/></Cd><Cd glow="#F59E0B"><SN value={subObj.credits} label="CREDITS" color="#F59E0B"/></Cd></div>
<ST color="#F59E0B">📋 ASSIGNMENTS</ST>{subObj.assignments.map(a=><Cd key={a.id} glow={a.done?'#10B981':''} cl="mb-2" onClick={()=>toggleAssign(a.id)}><div className="flex items-center gap-3"><div className={`w-6 h-6 rounded-full border-2 flex items-center justify-center text-xs flex-shrink-0 ${a.done?'border-green-400 bg-green-400/20 text-green-400':'border-gray-600'}`}>{a.done&&'✓'}</div><div className="flex-1"><div className={`text-sm font-bold ${a.done?'line-through opacity-50':''}`} style={{fontFamily:F.r}}>{a.title}</div></div></div></Cd>)}<Bt color="#F59E0B" v="outline" cl="w-full" onClick={()=>setView('assign')}>+ ASSIGNMENT</Bt>
<ST color="#3B82F6">📁 PROJECTS</ST>{subObj.projects.map(p=><Cd key={p.id} glow={pStatC[p.status]} cl="mb-2"><div className="flex items-center justify-between"><div><div className="text-sm font-bold" style={{fontFamily:F.r}}>{p.title}</div>{p.desc&&<div className="text-[10px] lc2" style={{color:'#94A3B8'}}>{p.desc}</div>}</div><div className="flex gap-1">{(['pending','progress','done'] as const).map(s=><button key={s} onClick={()=>updateProjStatus(p.id,s)} className="text-[8px] px-1.5 py-0.5 rounded font-bold" style={{background:p.status===s?`${pStatC[s]}20`:'transparent',color:p.status===s?pStatC[s]:'#475569',border:`1px solid ${p.status===s?pStatC[s]+'40':'transparent'}`}}>{s==='progress'?'WIP':s.toUpperCase()}</button>)}</div></div></Cd>)}<Bt color="#3B82F6" v="outline" cl="w-full" onClick={()=>setView('proj')}>+ PROJECT</Bt></>}
{view==='assign'&&<><Bt sm v="ghost" color={C.c} onClick={()=>setView('sub')} cl="mb-2">← BACK</Bt><Cd glow="#F59E0B"><div className="space-y-3"><In value={aTitle} onChange={setATitle} placeholder="Assignment title"/><Bt color="#F59E0B" cl="w-full" onClick={addAssign}>ADD (+25 XP on complete)</Bt></div></Cd></>}
{view==='proj'&&<><Bt sm v="ghost" color={C.c} onClick={()=>setView('sub')} cl="mb-2">← BACK</Bt><Cd glow="#3B82F6"><div className="space-y-3"><In value={pTitle} onChange={setPTitle} placeholder="Project title"/><textarea value={pDesc} onChange={e=>setPDesc(e.target.value)} placeholder="Description..." className="w-full px-3 py-2.5 rounded-lg text-sm text-white placeholder:text-gray-600 outline-none border h-24 resize-none" style={{background:'rgba(255,255,255,.03)',borderColor:'rgba(255,255,255,.06)',fontFamily:F.r}}/><Bt color="#3B82F6" cl="w-full" onClick={addProject}>ADD (+50 XP on complete)</Bt></div></Cd></>}
</div>;}

/* ═══ MEDIA ANALYSIS ═══ */
function Media({addXP,mediaItems,setMediaItems}:{addXP:(n:number,s?:Partial<Stats>)=>void;mediaItems:MediaItem[];setMediaItems:(m:MediaItem[])=>void}){
const[view,setView]=useState<'home'|'detail'|'add'>('home');
const[selItem,setSelItem]=useState<string>('');
const[mName,setMName]=useState('');const[mType,setMType]=useState<'image'|'video'>('image');const[mNotes,setMNotes]=useState('');const[mTags,setMTags]=useState('');
const[tsTime,setTsTime]=useState('');const[tsNote,setTsNote]=useState('');
const item=mediaItems.find(m=>m.id===selItem);
const addItem=()=>{if(!mName)return;const m:MediaItem={id:uid(),type:mType,name:mName,date:td(),notes:mNotes,tags:mTags.split(',').map(t=>t.trim()).filter(Boolean),analysis:'',timestamps:[]};const nm=[m,...mediaItems];setMediaItems(nm);sv('media',nm);addXP(15,{KNW:1});setView('home');setMName('');setMNotes('');setMTags('')};
const updateNotes=(notes:string)=>{const nm=mediaItems.map(m=>m.id===selItem?{...m,notes}:m);setMediaItems(nm);sv('media',nm)};
const addTimestamp=()=>{if(!tsTime||!tsNote)return;const nm=mediaItems.map(m=>m.id===selItem?{...m,timestamps:[...(m.timestamps||[]),{time:tsTime,note:tsNote}]}:m);setMediaItems(nm);sv('media',nm);setTsTime('');setTsNote('')};
const updateAnalysis=(analysis:string)=>{const nm=mediaItems.map(m=>m.id===selItem?{...m,analysis}:m);setMediaItems(nm);sv('media',nm)};
const deleteItem=(id:string)=>{const nm=mediaItems.filter(m=>m.id!==id);setMediaItems(nm);sv('media',nm);setView('home')};
const analyzeImage=()=>{const desc=`[Offline Analysis] Image "${item?.name}" logged on ${item?.date}. Tags: ${item?.tags.join(', ')||'none'}. ${item?.notes?'User notes: '+item.notes:'No notes yet.'}`;updateAnalysis(desc);addXP(20,{KNW:1,INT:1})};
const analyzeVideo=()=>{const desc=`[Offline Analysis] Video "${item?.name}" logged on ${item?.date}. ${(item?.timestamps||[]).length} timestamp notes. Tags: ${item?.tags.join(', ')||'none'}. ${item?.notes?'Notes: '+item.notes:''}`;updateAnalysis(desc);addXP(20,{KNW:1,INT:1})};
return<div className="space-y-5">
{view==='home'&&<><ST color="#EC4899">🖼️ MEDIA ANALYSIS</ST>
<Cd glow="#EC4899"><div className="text-[10px] tracking-[2px] font-bold mb-2" style={{fontFamily:F.o,color:'#EC4899'}}>OFFLINE-FIRST TOOLS</div><div className="text-xs leading-relaxed" style={{color:'#94A3B8'}}>Log and analyze your study materials, workout photos, progress images, lecture videos, and more. All data stored locally on your device.</div></Cd>
<div className="grid grid-cols-2 gap-2"><Cd glow="#EC4899"><SN icon="🖼️" value={mediaItems.filter(m=>m.type==='image').length} label="IMAGES" color="#EC4899"/></Cd><Cd glow="#8B5CF6"><SN icon="🎬" value={mediaItems.filter(m=>m.type==='video').length} label="VIDEOS" color="#8B5CF6"/></Cd></div>
<div className="grid grid-cols-2 gap-2">
{[{i:'📸',l:'Study Screenshot',t:'image' as const},{i:'📝',l:'Notes Photo',t:'image' as const},{i:'💪',l:'Progress Photo',t:'image' as const},{i:'📐',l:'Formula/Diagram',t:'image' as const},{i:'🎥',l:'Lecture Video',t:'video' as const},{i:'🏋️',l:'Workout Video',t:'video' as const}].map(q=><Cd key={q.l} glow={q.t==='image'?'#EC4899':'#8B5CF6'} onClick={()=>{setMType(q.t);setMName(q.l);setView('add')}}><div className="text-center"><div className="text-xl mb-0.5">{q.i}</div><div className="text-[8px] font-bold tracking-[1px]" style={{fontFamily:F.r,color:q.t==='image'?'#EC4899':'#8B5CF6'}}>{q.l.toUpperCase()}</div></div></Cd>)}
</div>
<Bt color="#EC4899" cl="w-full" onClick={()=>{setMName('');setView('add')}}>+ LOG MEDIA ITEM</Bt>
<ST color="#EC4899">📋 MEDIA LOG</ST>{mediaItems.slice(0,10).map(m=><Cd key={m.id} cl="mb-2" onClick={()=>{setSelItem(m.id);setView('detail')}}><div className="flex items-center gap-3"><div className="text-xl">{m.type==='image'?'🖼️':'🎬'}</div><div className="flex-1 min-w-0"><div className="text-sm font-bold truncate" style={{fontFamily:F.r}}>{m.name}</div><div className="text-[9px]" style={{color:'#475569'}}>{m.date}·{m.tags.length} tags{m.analysis?' · ✓ Analyzed':''}</div></div></div></Cd>)}
<div className="text-[8px] text-center p-2 rounded-lg" style={{background:'rgba(255,255,255,.01)',color:'#334155',fontFamily:F.r}}>⚠️ Media content processed locally. You control all imported data and can delete anytime.</div></>}
{view==='add'&&<><Bt sm v="ghost" color={C.c} onClick={()=>setView('home')} cl="mb-2">← BACK</Bt><Cd glow="#EC4899"><div className="space-y-3"><div className="text-[10px] tracking-[2px] font-bold" style={{fontFamily:F.o,color:'#EC4899'}}>LOG MEDIA</div><div className="flex gap-2"><Bt sm color="#EC4899" v={mType==='image'?'solid':'outline'} onClick={()=>setMType('image')}>🖼️ IMAGE</Bt><Bt sm color="#8B5CF6" v={mType==='video'?'solid':'outline'} onClick={()=>setMType('video')}>🎬 VIDEO</Bt></div><In value={mName} onChange={setMName} placeholder="Name / Description"/><In value={mTags} onChange={setMTags} placeholder="Tags (comma separated)"/><textarea value={mNotes} onChange={e=>setMNotes(e.target.value)} placeholder="Notes about this media..." className="w-full px-3 py-2.5 rounded-lg text-sm text-white placeholder:text-gray-600 outline-none border h-24 resize-none" style={{background:'rgba(255,255,255,.03)',borderColor:'rgba(255,255,255,.06)',fontFamily:F.r}}/><Bt color="#EC4899" cl="w-full" onClick={addItem}>SAVE (+15 XP)</Bt></div></Cd></>}
{view==='detail'&&item&&<><Bt sm v="ghost" color={C.c} onClick={()=>setView('home')} cl="mb-2">← BACK</Bt><ST color={item.type==='image'?'#EC4899':'#8B5CF6'}>{item.type==='image'?'🖼️':'🎬'} {item.name.toUpperCase()}</ST>
<Cd glow={item.type==='image'?'#EC4899':'#8B5CF6'}><div className="space-y-3"><div className="flex justify-between"><span className="text-[9px] tracking-wider" style={{fontFamily:F.r,color:'#475569'}}>{item.date}</span><span className="text-[9px] px-1.5 py-0.5 rounded" style={{background:item.type==='image'?'rgba(236,72,153,.1)':'rgba(139,92,246,.1)',color:item.type==='image'?'#EC4899':'#8B5CF6'}}>{item.type.toUpperCase()}</span></div>{item.tags.length>0&&<div className="flex gap-1 flex-wrap">{item.tags.map((t,i)=><span key={i} className="text-[8px] px-1.5 py-0.5 rounded" style={{background:'rgba(0,229,255,.08)',color:C.c}}>#{t}</span>)}</div>}
<div><div className="text-[9px] tracking-wider mb-1" style={{fontFamily:F.r,color:'#94A3B8'}}>NOTES</div><textarea value={item.notes} onChange={e=>updateNotes(e.target.value)} className="w-full px-3 py-2 rounded-lg text-sm text-white outline-none border h-24 resize-none" style={{background:'rgba(255,255,255,.03)',borderColor:'rgba(255,255,255,.06)',fontFamily:F.r}}/></div></div></Cd>
{item.type==='video'&&<Cd glow="#8B5CF6"><div className="text-[10px] tracking-[2px] font-bold mb-2" style={{fontFamily:F.o,color:'#8B5CF6'}}>⏱ TIMESTAMP NOTES</div>{(item.timestamps||[]).map((ts,i)=><div key={i} className="flex gap-2 py-1.5 border-t first:border-0" style={{borderColor:'rgba(255,255,255,.04)'}}><span className="text-xs font-bold flex-shrink-0" style={{fontFamily:F.m,color:'#8B5CF6'}}>{ts.time}</span><span className="text-xs" style={{color:'#94A3B8'}}>{ts.note}</span></div>)}<div className="flex gap-2 mt-2"><In value={tsTime} onChange={setTsTime} placeholder="00:00" cl="w-20"/><In value={tsNote} onChange={setTsNote} placeholder="Note at timestamp"/><Bt sm color="#8B5CF6" onClick={addTimestamp}>+</Bt></div></Cd>}
<Cd glow="#10B981"><div className="text-[10px] tracking-[2px] font-bold mb-2" style={{fontFamily:F.o,color:'#10B981'}}>🔍 ANALYSIS</div>{item.analysis?<div className="text-xs leading-relaxed" style={{color:'#94A3B8'}}>{item.analysis}</div>:<div className="text-xs" style={{color:'#475569'}}>No analysis yet. Run offline analysis below.</div>}<div className="flex gap-2 mt-3"><Bt color="#10B981" cl="flex-1" onClick={item.type==='image'?analyzeImage:analyzeVideo}>🔍 ANALYZE (+20 XP)</Bt></div></Cd>
<Cd glow="#EF4444"><Bt color="#EF4444" v="outline" cl="w-full" onClick={()=>deleteItem(item.id)}>🗑️ DELETE ITEM</Bt></Cd></>}
</div>;}

/* ═══ MAIN APP ═══ */
export default function App(){
const[tab,setTab]=useState<Tab>('home');
const{prof,setProf,stats,addXP,lvl,setLvl,doStreak}=useXP();
const[workouts,setWorkouts]=useState<Workout[]>(()=>ld('workouts',[]));
const[studySes,setStudySes]=useState<StudySes[]>(()=>ld('study_ses',[]));
const[codingSes,setCodingSes]=useState<CodingSes[]>(()=>ld('cs',[]));
const[txs,setTxs]=useState<Tx[]>(()=>ld('txs',[]));
const[goals,setGoals]=useState<Goal[]>(()=>ld('goals',[]));
const[habits,setHabits]=useState<Habit[]>(()=>ld('habits',[
{id:'h1',name:'Exercise',icon:'💪',dates:[],streak:0,xpPer:25},
{id:'h2',name:'Read 20 pages',icon:'📚',dates:[],streak:0,xpPer:20},
{id:'h3',name:'Drink 3L Water',icon:'💧',dates:[],streak:0,xpPer:15},
]));
const[tasks,setTasks]=useState<Task[]>(()=>ld('tasks',[]));
const[notes,setNotes]=useState<Note[]>(()=>ld('notes',[]));
const[fcs,setFCs]=useState<FC[]>(()=>ld('fcs',[]));
const[qr,setQR]=useState<QR[]>(()=>ld('qr',[]));
const[weights,setWeights]=useState<WtEntry[]>(()=>ld('weights',[]));
const[water,setWater]=useState<WaterEntry[]>(()=>ld('water',[]));
const[edu,setEdu]=useState<EduProfile>(()=>ld('edu',defEdu));
const[semesters,setSemesters]=useState<Semester[]>(()=>ld('semesters',[]));
const[mediaItems,setMediaItems]=useState<MediaItem[]>(()=>ld('media',[]));
const[dl,setDL]=useState<DL>(()=>ld(`dl_${td()}`,defDL()));
const[dls,setDLs]=useState<DL[]>(()=>ld('day_logs',[]));
useEffect(()=>{sv(`dl_${td()}`,dl)},[dl]);
useEffect(()=>{const t=td();const ex=dls.findIndex(d=>d.date===t);let nl:DL[];if(ex>=0){nl=[...dls];nl[ex]=dl}else nl=[...dls,dl];setDLs(nl);sv('day_logs',nl)},[dl]);
const[quests,setQuests]=useState<Quest[]>(()=>{const s=ld<Quest[]>(`q_${td()}`,[]);if(s.length>0)return s;return[
{id:uid(),title:'Complete 1 Workout',mod:'fit',target:1,current:0,xp:50,done:false,date:td()},
{id:uid(),title:'Study 30 min',mod:'study',target:30,current:0,xp:60,done:false,date:td()},
{id:uid(),title:'Complete 3 Habits',mod:'prod',target:3,current:0,xp:40,done:false,date:td()},
{id:uid(),title:'Earn 200 XP',mod:'general',target:200,current:0,xp:80,done:false,date:td()},
]});
useEffect(()=>{const nq=quests.map(q=>{let c=q.current;if(q.mod==='fit')c=workouts.filter(w=>w.date===td()).length;if(q.mod==='study')c=dl.sMin;if(q.mod==='prod')c=dl.habits;if(q.mod==='general')c=dl.xp;const done=c>=q.target;if(done&&!q.done)addXP(q.xp,{DIS:1});return{...q,current:c,done}});setQuests(nq);sv(`q_${td()}`,nq)},[dl,workouts]);
const[achs,setAchs]=useState<Ach[]>(()=>ld('achs',[
{id:'a1',title:'First Blood',desc:'Complete first workout',icon:'⚔️',tier:'Bronze',cat:'Fitness',earned:false},
{id:'a2',title:'Scholar',desc:'2hr total study',icon:'📚',tier:'Silver',cat:'Study',earned:false},
{id:'a3',title:'Code Warrior',desc:'10 coding sessions',icon:'💻',tier:'Gold',cat:'Coding',earned:false},
{id:'a4',title:'Persistent',desc:'5-day streak',icon:'🔥',tier:'Platinum',cat:'Consistency',earned:false},
{id:'a5',title:'Gate Conqueror',desc:'Reach Level 10',icon:'🏆',tier:'Diamond',cat:'Progression',earned:false},
{id:'a6',title:'XP Hunter',desc:'5000 total XP',icon:'⚡',tier:'Gold',cat:'Progression',earned:false},
{id:'a7',title:'Quiz Master',desc:'Score 100%',icon:'🧠',tier:'Diamond',cat:'Knowledge',earned:false},
{id:'a8',title:'Habit Machine',desc:'All habits done',icon:'🔗',tier:'Platinum',cat:'Consistency',earned:false},
{id:'a9',title:'Shadow Monarch',desc:'Reach S-Rank',icon:'👑',tier:'Mythic',cat:'Progression',earned:false},
{id:'a10',title:'Iron Will',desc:'30-day streak',icon:'💎',tier:'Mythic',cat:'Consistency',earned:false},
{id:'a11',title:'Board Ready',desc:'10 board tests',icon:'🎓',tier:'Gold',cat:'Study',earned:false},
{id:'a12',title:'Finance Guru',desc:'50 transactions',icon:'💰',tier:'Silver',cat:'Finance',earned:false},
]));
useEffect(()=>{const ts=studySes.reduce((a,b)=>a+b.dur,0);const allH=habits.length>0&&habits.every(h=>h.dates.includes(td()));const pq=qr.some(r=>r.sc===r.tot&&r.tot>0);const na=achs.map(a=>{if(a.earned)return a;let e=false;if(a.id==='a1'&&workouts.length>0)e=true;if(a.id==='a2'&&ts>=120)e=true;if(a.id==='a3'&&codingSes.length>=10)e=true;if(a.id==='a4'&&prof.streak>=5)e=true;if(a.id==='a5'&&prof.level>=10)e=true;if(a.id==='a6'&&prof.totalXp>=5000)e=true;if(a.id==='a7'&&pq)e=true;if(a.id==='a8'&&allH)e=true;if(a.id==='a9'&&['S','SS','SSS'].includes(prof.rank))e=true;if(a.id==='a10'&&prof.streak>=30)e=true;if(a.id==='a11'&&qr.filter(r=>r.mode==='board').length>=10)e=true;if(a.id==='a12'&&txs.length>=50)e=true;return e?{...a,earned:true}:a});if(JSON.stringify(na)!==JSON.stringify(achs)){setAchs(na);sv('achs',na)};},[prof,workouts,studySes,codingSes,qr,habits,txs]);
useEffect(()=>{doStreak()},[]);
const resetAll=()=>{const keys=['prof','stats','workouts','study_ses','cs','txs','goals','habits','tasks','notes','fcs','qr','day_logs','achs','weights','water','edu','semesters','media',`q_${td()}`,`dl_${td()}`];keys.forEach(k=>localStorage.removeItem('sf_'+k));window.location.reload()};
const render=()=>{switch(tab){
case'home':return<Home prof={prof} stats={stats} quests={quests} achs={achs} dl={dl} setTab={setTab}/>;
case'fit':return<Fit addXP={addXP} workouts={workouts} setWorkouts={setWorkouts} dl={dl} setDL={setDL} weights={weights} setWeights={setWeights} water={water} setWater={setWater}/>;
case'study':return<Study addXP={addXP} ses={studySes} setSes={setStudySes} notes={notes} setNotes={setNotes} dl={dl} setDL={setDL}/>;
case'board':return<Board addXP={addXP} prof={prof} qr={qr} setQR={setQR} dl={dl} setDL={setDL}/>;
case'exam':return<Exam addXP={addXP} prof={prof} qr={qr} setQR={setQR}/>;
case'cards':return<Cards addXP={addXP} fcs={fcs} setFCs={setFCs}/>;
case'code':return<Code addXP={addXP} cs={codingSes} setCs={setCodingSes} dl={dl} setDL={setDL}/>;
case'math':return<MathM/>;
case'finance':return<Finance txs={txs} setTxs={setTxs} goals={goals} setGoals={setGoals}/>;
case'prod':return<Prod addXP={addXP} habits={habits} setHabits={setHabits} tasks={tasks} setTasks={setTasks} dl={dl} setDL={setDL}/>;
case'know':return<Know/>;
case'stats':return<Analytics prof={prof} stats={stats} dls={dls} workouts={workouts} ses={studySes} cs={codingSes} txs={txs} qr={qr}/>;
case'cfg':return<Cfg prof={prof} setProf={setProf} resetAll={resetAll}/>;
case'college':return<College addXP={addXP} edu={edu} setEdu={setEdu} semesters={semesters} setSemesters={setSemesters} dl={dl} setDL={setDL}/>;
case'media':return<Media addXP={addXP} mediaItems={mediaItems} setMediaItems={setMediaItems}/>;
default:return null;
}};
return<div className="min-h-screen relative" style={{background:C.bg}}>
<div className="fixed top-0 left-1/2 -translate-x-1/2 w-[500px] h-[500px] pointer-events-none z-0" style={{background:`radial-gradient(circle,${C.p}06,transparent 70%)`}}/>
<div className="relative z-10 max-w-lg mx-auto px-4 pt-4 pb-24">
{tab!=='home'&&<button onClick={()=>setTab('home')} className="flex items-center gap-2 mb-4 text-xs font-bold tracking-wider" style={{fontFamily:F.r,color:'#475569'}}>← HOME</button>}
{render()}
</div>
<div className="fixed bottom-0 left-0 right-0 z-40"><div className="max-w-lg mx-auto"><div className="border-t overflow-x-auto" style={{background:'rgba(5,8,22,.94)',backdropFilter:'blur(16px)',borderColor:`${C.c}08`}}><div className="flex min-w-max">{TABS.map(t=>{const a=tab===t.id;return<button key={t.id} onClick={()=>setTab(t.id)} className="flex-1 min-w-[48px] flex flex-col items-center py-2 px-0.5 relative" style={{color:a?C.c:'#334155'}}>{a&&<div className="absolute top-0 left-1/2 -translate-x-1/2 w-6 h-[2px] rounded-full" style={{background:C.c,boxShadow:`0 0 8px ${C.c}`}}/>}<span className="text-[14px] mb-0.5">{t.icon}</span><span className="text-[6px] font-bold tracking-wider" style={{fontFamily:F.o}}>{t.l.toUpperCase()}</span></button>})}</div></div></div></div>
<LvlUp d={lvl} onClose={useCallback(()=>setLvl(p=>({...p,show:false})),[setLvl])}/>
</div>;}
